### ISSUE TITLE
Errors when using docker-compose on Win 10 WSL with docker deamon on windows and linux containers

### ISSUE THREAD

**Issue by Philtard** [bitnami/bitnami-docker-wordpress#108]
# Fatal error on docker-compose up in WSL with dockerdaemon on win10 host, but docker-ce and docker-compose client on wsl (16 lts buntu)

docker-compose up stops with an error on the current master on the system described below. Workaround for the initial problem possible.

```Code
bitnami-docker-wordpress git/master
❯ docker-compose up
ERROR: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version
```

**Steps to reproduce the issue:**

1. open wsl
    - winkey + r -> type '`wsl`' or '`bash` or whatever necessary for a terminal to pop up in which `> uname -a` returns `*sth* *sth* **Microsoft** *sth* *sth*`

1. `> git clone git@github.com:bitnami/bitnami-docker-wordpress.git`
1. `cd bitnami-docker-wordpress`

    ** just to be sure to not use the windows docker-compose.exe, have a look at it with 'which'

```Terminal
    > which docker-compose
    /usr/local/bin/docker-compose
```

1. `❯ docker-compose up`

**Describe the results you received:**

```Error
**ERROR**: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version
```

**Describe the results you expected:**

This was exactly what I expected, well, something in the form of *error* bla bla *version*  bla bla *not supported* because I sure deserved it.

**Additional information you deem important (e.g. issue happens only occasionally):**

I found some discussions about this Errormessage -> looks like there was an agreement towards won't fix with one participant  suggesting, to, at least, change the error message text, but there was not enough confident in his statement, so that discussion is off the table I guess.

## Workaround

I get passed this error by changing the version in the docker-compose.yml file from "2" to "2.1"

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index d704716..f47c4c2 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,4 +1,4 @@
-version: '2'
+version: '2.1'
 services:
   mariadb:
     image: 'bitnami/mariadb:latest'
(END)
```

docker-compose.yml file:

```yml
❯ cat docker-compose.yml
version: '2.1'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'wordpress_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
```

## getting passed the initial error to this error message:

```Terminal
❯ docker-compose up
Creating network "bitnamidockerwordpress_default" with the default driver
Pulling mariadb (bitnami/mariadb:latest)...
latest: Pulling from bitnami/mariadb
ERROR: cannot download image with operating system "linux" when requesting "windows"
```

Ok, some progress...
The image cannot be downloaded because something somewhere requested windows, but something somehow knows about being linux. My knowledge about the download requests format is zero, so didn't look into that now.

My next step was to manually pull the images with `docker pull imagename` commmand. Just to be sure, i ran the quick hello-world docker images to verify that the environment is actually functional:

```Terminal
> docker run hello-world                                                                                                                                                                   /mnt/c/Users/phili@C137
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
ca4f61b1923c: Pull complete
Digest: sha256:66ef312bbac49c39a89aa9bcc3cb4f3c9e7de3788c944158df3ee0176d32b751
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
....
```

So no problems here. Proceeding to pull the _bitnami/wordpress:latest_ (exact name copied from the docker-compose.yml file) image:

```Terminal
> docker pull bitnami/wordpress:latest                                                                                                         ~@C137
latest: Pulling from bitnami/wordpress
21a7e111de8c: Pull complete
65e50e28a4a4: Pull complete
b94a89aafdb1: Pull complete
7487ef2491c8: Pull complete
fbabf81a333a: Pull complete
f532281efb89: Pull complete
9fee6c568010: Pull complete
a4671ab5a144: Pull complete
4034e6ff4e6b: Pull complete
b899355d3883: Pull complete
efaf81eb449e: Pull complete
c8a4ab86571c: Pull complete
db4cefe8f824: Pull complete
Digest: sha256:19c5227e766796e3dc7987e91dce84e0e71580428c4b185608c4f673075a7a75
Status: Downloaded newer image for bitnami/wordpress:latest
```

and the database pull didn't make any problems either:

```Terminal
> docker pull bitnami/mariadb:latest                                                                                                           ~@C137
latest: Pulling from bitnami/mariadb
21a7e111de8c: Already exists
65e50e28a4a4: Already exists
b94a89aafdb1: Already exists
7487ef2491c8: Already exists
fbabf81a333a: Already exists
f532281efb89: Already exists
fe9e6da83046: Pull complete
9198bc632af9: Pull complete
b766f87309cd: Pull complete
Digest: sha256:41204a6314129a9747a4e8378c7dc28e7d6bfda1e9031f0aa280a422d39a3918
Status: Downloaded newer image for bitnami/mariadb:latest

```

current 'docker images' return:

```Terminal
> docker images                                                                                                                                ~@C137
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
bitnami/mariadb     latest              27345301f2ea        12 days ago         865MB
bitnami/wordpress   latest              9011a3dfb14c        13 days ago         487MB
hello-world         latest              f2a91732366c        7 weeks ago         263kB
```

## Having the images, next try to `docker-compose up`

At first glance it looks like it's working just fine until the connection to the database should be established. After i think 36 tries it gives up and the containers stop. Don't know if it's of any use, but here is some log output and config.

```bash
Creating bitnamidockerwordpress_mariadb_1   ... done
Creating bitnamidockerwordpress_mariadb_1   ...
Creating bitnamidockerwordpress_wordpress_1 ... done
Attaching to bitnamidockerwordpress_mariadb_1, bitnamidockerwordpress_wordpress_1
mariadb_1    |
wordpress_1  |
mariadb_1    | Welcome to the Bitnami mariadb container
mariadb_1    | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1    | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1    | Send us your feedback at containers@bitnami.com
mariadb_1    |
mariadb_1    | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
wordpress_1  | Welcome to the Bitnami wordpress container
wordpress_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
wordpress_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues
wordpress_1  | Send us your feedback at containers@bitnami.com
wordpress_1  |
wordpress_1  | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1    | nami    INFO  Initializing mariadb
mariadb_1    | mariadb INFO
mariadb_1    | mariadb INFO  ########################################################################
mariadb_1    | mariadb INFO   Installation parameters for mariadb:
mariadb_1    | mariadb INFO     Persisted data and properties have been restored.
mariadb_1    | mariadb INFO     Any input specified will not take effect.
mariadb_1    | mariadb INFO   This installation requires no credentials.
mariadb_1    | mariadb INFO  ########################################################################
mariadb_1    | mariadb INFO
mariadb_1    | nami    INFO  mariadb successfully initialized
mariadb_1    | INFO  ==> Starting mariadb...
mariadb_1    | INFO  ==> Starting mysqld_safe...
mariadb_1    | Warning: World-writable config file '/opt/bitnami/mariadb/conf/my.cnf' is ignored
mariadb_1    | Warning: World-writable config file '/opt/bitnami/mariadb/conf/my.cnf' is ignored
mariadb_1    | 180109 05:32:33 mysqld_safe Logging to '/opt/bitnami/mariadb/data/8a481b0947a4.err'.
mariadb_1    | 180109 05:32:33 mysqld_safe Starting mysqld daemon with databases from /opt/bitnami/mariadb/data
wordpress_1  | nami    INFO  Initializing apache
wordpress_1  | apache  INFO  ==> Reconfiguring PID file location...
wordpress_1  | nami    INFO  apache successfully initialized
wordpress_1  | nami    INFO  Initializing php
wordpress_1  | nami    INFO  php successfully initialized
wordpress_1  | nami    INFO  Initializing mysql-client
wordpress_1  | nami    INFO  mysql-client successfully initialized
wordpress_1  | nami    INFO  Initializing wordpress
wordpress_1  | mysql-c INFO  Trying to connect to MySQL server
bitnamidockerwordpress_mariadb_1 exited with code 0

```

but in the second to last line, when trying to connect to MySQL server, it eventually times out. The Webserver is not responding to HttpRequests (not on port 80, or 443).

The only warning sounds kinda harmless: `Warning: World-writable config file '/opt/bitnami/mariadb/conf/my.cnf' is ignored`. But I thought to have a look at this `my.cnf`file, so I `docker start bitnamidockerwordpress_mariadb_1' again and have jump inside with 'docker exec -ti bitnamidockerwordpress_mariadb_1 /bin/bash':

my.cnf (which is ignored) contains:

```ini
root@8a481b0947a4:/opt/bitnami/mariadb/conf# cat my.cnf
[mysqladmin]
user=bn_wordpress

[mysqld]
skip-name-resolve
explicit_defaults_for_timestamp
basedir=/opt/bitnami/mariadb
port=3306
socket=/opt/bitnami/mariadb/tmp/mysql.sock
tmpdir=/opt/bitnami/mariadb/tmp
max_allowed_packet=16M
bind-address=0.0.0.0
pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
log-error=/opt/bitnami/mariadb/logs/mysqld.log
character-set-server=UTF8
collation-server=utf8_general_ci

[client]
port=3306
socket=/opt/bitnami/mariadb/tmp/mysql.sock
default-character-set=UTF8

[manager]
port=3306
socket=/opt/bitnami/mariadb/tmp/mysql.sock
pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid

!include /bitnami/mariadb/conf/my_custom.cnf
root@8a481b0947a4:/opt/bitnami/mariadb/conf#
```

What catches my attention are the paths to the socket files. If I'd not be sleepy and hungry now, that's where I would probably fire up google and see if this is known to cause problems on a windows docker host for linux containers.

## Just for fun, I switch all docker settings to windows and see what happens in powershell with windows' docker-compose.exe client

I don't know if, it's supposed to work like this, but it didn't (see the Error below). Doesn't relate to this issue anyway.

```command
D:\D_Workspace\git\bitnami-docker-wordpress>docker-compose.exe up
Creating network "bitnamidockerwordpress_default" with the default driver
Creating volume "bitnamidockerwordpress_wordpress_data" with local driver
Creating volume "bitnamidockerwordpress_mariadb_data" with local driver
Pulling mariadb (bitnami/mariadb:latest)...
latest: Pulling from bitnami/mariadb
ERROR: image operating system "linux" cannot be used on this platform

D:\D_Workspace\git\bitnami-docker-wordpress>docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
hello-world         latest              eb6bb16eb0d9        7 weeks ago         249MB

D:\D_Workspace\git\bitnami-docker-wordpress>docker pull bitnami/mariadb
Using default tag: latest
latest: Pulling from bitnami/mariadb
image operating system "linux" cannot be used on this platform
```

## The problem has to do with the environment

Also, this exact version (the current master) works without any hickups on all my other native linux machines / VMs, ... that is both of them, ... same OS. .... anyway.

# Versions following the template of the Win10 + WSL Environment that caused problems

**Version**

Output of `> docker version`:

```Yml
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.24)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:15:52 2017
  OS/Arch:      windows/amd64
  Experimental: true

```

- Output of `> docker info`:

```Yml
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 2
Server Version: 17.12.0-ce
Storage Driver: windowsfilter (windows) lcow (linux)
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.96GiB
Name: C137
ID: 34NT:J47T:MDGD:DH3U:63J2:2E3X:AKHA:YPVA:ZOEI:E4EB:UXVW:R3TL
Docker Root Dir: C:\ProgramData\Docker\lcow
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 29
 System Time: 2018-01-09T03:06:13.6232992+01:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

- Output of `> docker-compose version` (if applicable):

```Terminal
docker-compose version 1.18.0-rc2, build 189468b
docker-py version: 2.6.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Probably unrelated, but anyway worth mentioning due to the constant changes on how to setup windows daemon <-> linux docker client from WSL working environments these days:

Expose daemon on tcp://localhost:2375 without TLS and Enable Linux containers on Windows are both enabled in the windows docker daemon.

To make the wsl / linux docker and docker-compose binaries work I added following line to my *.zshrc (*.bashrc):

```Bash
export DOCKER_HOST="tcp://0.0.0.0:2375"
```
