### ISSUE TITLE
Add phpmyadmin container

### ISSUE THREAD

**Issue by stephane-r** [bitnami/bitnami-docker-wordpress#109]
**Description**

I would like add phpMyAdmin container to `docker-compose.yml`. I've try to add this :

```
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: bn_wordpress
    MYSQL_ROOT_PASSWORD: bitnami_wordpress
```

But without result.

**Additional information you deem important (e.g. issue happens only occasionally):**

I would like add phpMyAdmin for admin my data base, export and import sql file.

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 15
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 207
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-104-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.702GiB
Name: stephane-X555LAB
ID: 4W7X:K4OM:56UV:VJJO:QIET:OR3L:TSN6:W4C2:HFE6:UUXL:M26Q:XHSO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.8.1, build 878cff1
docker-py version: 1.10.4
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Ubuntu 16.04.

Thank you !

**Comment by stephane-r** [comment]
Hi @juan131 

Thank you, it work very nice !

**Comment by juan131** [comment]
Hi @stephane-r 

Great to heart that! I am glad it worked 😄

**Comment by xermus** [comment]
How do you secure the login to PHPMyadmin? (I meann so that you do NOT allow an empty password)

**Comment by juan131** [comment]
Hi @xermus 

Are you using the `docker-composse.yaml` I previously shared? Please note that it uses **ALLOW_EMPTY_PASSWORD=yes**.

There's another env. variable that allows you to configure the credentials, see **PHPMYADMIN_ALLOW_NO_PASSWORD**. You can find more information in the link below:

https://github.com/bitnami/bitnami-docker-phpmyadmin#environment-variables

**Comment by xermus** [comment]
Hi @juan131!

I am using bitnami/mariadb, bitnami/wordpress and bitnami/phpmyadmin. I think the basic configuration is meant to be for development. I am now trying to make the above combination work with a password implemented so I can see how it would behave in a production environment.

Here is my docker-compose.yml file:

```yaml   

version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'wordpress_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  phpmyadmin: 
      image: bitnami/phpmyadmin:latest
      depends_on:
        - mariadb
      ports:
        - '580:80'
        - '5443:443'
      volumes:
        - phpmyadmin_data:/bitnami
      environment:
        - PHPMYADMIN_ALLOW_NO_PASSWORD=false
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  phpmyadmin_data:
    driver: local    
```

When I set  ALLOW_EMPTY_PASSWORD=yes  to  "no" then I get cannot log in with an empty password in phpmyadmin, but I get another error there. What do I have to do in order to proceed here with a valid password?

**Comment by tompizmor** [comment]
Hi @xermus,

If you set ALLOW_EMPTY_PASSWORD=no, then you need to specify all the database password environment variables. 

I have added ` MARIADB_PASSWORD` and ` MARIADB_ROOT_PASSWORD` env vars to the mariadb container and `WORDPRESS_DATABASE_PASSWORD` to the wordpress container.

Please take a look to this docker-compose.yml based on the one you have shared.

```
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - MARIADB_PASSWORD=YOUR_WORDPRESS_DATABASE_PASSWORD
      - MARIADB_ROOT_PASSWORD=YOUR_ROOT_PASSWORD
      - ALLOW_EMPTY_PASSWORD=no
  wordpress:
    image: 'bitnami/wordpress:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'wordpress_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_DATABASE_PASSWORD=YOUR_WORDPRESS_DATABASE_PASSWORD
      - ALLOW_EMPTY_PASSWORD=no
  phpmyadmin:
      image: bitnami/phpmyadmin:latest
      depends_on:
        - mariadb
      ports:
        - '580:80'
        - '5443:443'
      volumes:
        - phpmyadmin_data:/bitnami
      environment:
        - PHPMYADMIN_ALLOW_NO_PASSWORD=false
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  phpmyadmin_data:
    driver: local
```

Note that `YOUR_ROOT_PASSWORD` and `YOUR_WORDPRESS_DATABASE_PASSWORD` are placeholders for your actual passwords.
