### ISSUE TITLE
wordpress on docker ZFS

### ISSUE THREAD

**Issue by Tri232** [bitnami/bitnami-docker-wordpress#111]
Description
On AWS linux ami, I first installed ZFS and configured docker to have docker backend on ZFS. After setting up docker on ZFS, installed docker-compose and curl docker-compose.yml. 
docker-compose.yml points to a remote database on a remote host. This is my docker-compose.yml
```
version: '2'
services:
  wordpress:
    image: 'bitnami/wordpress:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=<remote-host>
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=<username>
      - WORDPRESS_DATABASE_NAME=<DB_NAME>
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  wordpress_data:
    driver: local
```

After successfully creating a wordpress container instance, I modified the instance by adding a few plugins and themes. Now I intend to duplicate the docker instance but pointing to another database on the same remote host. So I ran the following command

`docker commit -a "ABC Team" -m "Some comment" <my-container-id> name:version1`

Now, to create a duplicate container 
`docker run -d --name <NEW_NAME> -p 4000:80 -t -i --env MARIADB_HOST=<remote-host> --env MARIADB_PORT_NUMBER=3306 --env WORDPRESS_DATABASE_NAME=<new_DBNAME> --env WORDPRESS_DATABASE_USER=<new_DBUSER> --env WORDPRESS_DATABASE_PASSWORD=<some-passoword> --restart always name:version1`

After this command a new container is created but the container tries to connect to the same old database and not the new one mentioned in docker run command. The docker inspect command however shows correct credentials. On further debugging I found the wp-config.php file of the new container has the same old Database configuration. 

Here is the docker version used. 
# docker version
```Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.4
 Git commit:   3dfb8343b139d6342acfd9975d7f1068b5b1c3d3
 Built:        Fri Nov 10 00:50:37 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.4
 Git commit:   402dd4a/17.06.2-ce
 Built:        Fri Nov 10 00:51:08 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
# docker info
```
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 17.06.2-ce
Storage Driver: zfs
 Zpool: error while getting pool information strconv.ParseUint: parsing "": invalid syntax
 Zpool Health: not available
 Parent Dataset: pool/docker
 Space Used By Parent: 489804288
 Space Available: 51363737376
 Parent Quota: no
 Compression: on
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.75-25.55.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.09
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 14.93GiB
Name: ip-192-168-253-3
ID: ZZRA:EL4G:M56P:TXI6:25D7:KAD5:5FPK:PXKV:FDMI:6RFX:GGZZ:7E46
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 21
 Goroutines: 30
 System Time: 2018-02-01T14:11:09.524168535+05:30
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

# docker-compose version
```docker-compose version 1.17.0, build ac53b73
docker-py version: 2.5.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

Pardon me for any mistakes found here as i'm just a beginner.
Truly appreciate your help.
Thanking in advance.

**Comment by Tri232** [comment]
Description
On AWS linux ami, I first installed ZFS and configured docker to have docker backend on ZFS. After setting up docker on ZFS, installed docker-compose and curl docker-compose.yml. 
docker-compose.yml points to a remote database on a remote host. This is my docker-compose.yml
```
version: '2'
services:
  wordpress:
    image: 'bitnami/wordpress:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=<remote-host>
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=<username>
      - WORDPRESS_DATABASE_NAME=<DB_NAME>
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  wordpress_data:
    driver: local
```

After successfully creating a wordpress container instance, I modified the instance by adding a few plugins and themes. Now I intend to duplicate the docker instance but pointing to another database on the same remote host. So I ran the following command

`docker commit -a "ABC Team" -m "Some comment" <my-container-id> name:version1`

Now, to create a duplicate container 
`docker run -d --name <NEW_NAME> -p 4000:80 -t -i --env MARIADB_HOST=<remote-host> --env MARIADB_PORT_NUMBER=3306 --env WORDPRESS_DATABASE_NAME=<new_DBNAME> --env WORDPRESS_DATABASE_USER=<new_DBUSER> --env WORDPRESS_DATABASE_PASSWORD=<some-passoword> --restart always name:version1`

After this command a new container is created but the container tries to connect to the same old database and not the new one mentioned in docker run command. The docker inspect command however shows correct credentials. On further debugging I found the wp-config.php file of the new container has the same old Database configuration. 

Here is the docker version used. 
`[]# docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.4
 Git commit:   3dfb8343b139d6342acfd9975d7f1068b5b1c3d3
 Built:        Fri Nov 10 00:50:37 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.4
 Git commit:   402dd4a/17.06.2-ce
 Built:        Fri Nov 10 00:51:08 2017
 OS/Arch:      linux/amd64
 Experimental: false
`

[]# docker info
`Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 17.06.2-ce
Storage Driver: zfs
 Zpool: error while getting pool information strconv.ParseUint: parsing "": invalid syntax
 Zpool Health: not available
 Parent Dataset: pool/docker
 Space Used By Parent: 489804288
 Space Available: 51363737376
 Parent Quota: no
 Compression: on
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.75-25.55.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.09
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 14.93GiB
Name: ip-192-168-253-3
ID: ZZRA:EL4G:M56P:TXI6:25D7:KAD5:5FPK:PXKV:FDMI:6RFX:GGZZ:7E46
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 21
 Goroutines: 30
 System Time: 2018-02-01T14:11:09.524168535+05:30
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
`

[]# docker-compose version
`docker-compose version 1.17.0, build ac53b73
docker-py version: 2.5.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016`

Pardon me for any mistakes found here as i'm just a beginner.
Truly appreciate your help.
Thanking in advance.
