### ISSUE TITLE
How to add plugins with the current Dockerfile?

### ISSUE THREAD

**Issue by KIVagant** [bitnami/bitnami-docker-wordpress#115]
Hello.

I'm trying to use this repo to build Wordpress image with my plugin preinstalled inside:

```
COPY rootfs /
COPY my-plugin.php /bitnami/wordpress/wp-content/plugins/my-plugin.php
```

This variant isn't good because only my file will be available in the `plugins` directory but all other will be missed.
Is it possible to add plugin(s) to the image that builds from this repo?

**Comment by KIVagant** [comment]
Looks like adding next line to the end of `app-entrypoint.sh` works fine:

```
ln -sf /my-plugin.php /bitnami/wordpress/wp-content/plugins/my-plugin.php
```

But is it the best option in my case?

**Comment by juan131** [comment]
Hi @KIVagant 

In order to pre-install it, the best option is to modify the **app-entrypoint.sh** file to install it. There are several ways to install it on that step:

 * Copy it from a local directory.
 * Download it from an URL.
 * Using the [WP Command Line](http://wp-cli.org/)
 * ...

Another alternative, will be to persist your application (more info at: https://github.com/bitnami/bitnami-docker-wordpress#persisting-your-application). Therefore, you can install your plugin from the your WP Admin board and, since you're persisting your plugin on a volume, you can restart your WP container and the plugin will be installed.

**Comment by KIVagant** [comment]
Hey, @juan131 
I understand that I can use Admin panel, but my goal is to install docker image with the plugin inside. 
After lot of tests I found this `app-entrypoint.sh` works for me:

```
#!/bin/bash -e

. /opt/bitnami/base/functions
. /opt/bitnami/base/helpers

print_welcome_page

if [[ "$1" == "nami" && "$2" == "start" ]] || [[ "$1" == "/init.sh" ]]; then
  . /init.sh
  nami_initialize apache php mysql-client wordpress
  info "Starting wordpress... "
  info "Installing plugin" && cp -rfn /myplugin.php /bitnami/wordpress/wp-content/plugins/myplugin.php

fi

exec tini -- "$@"
```

I don't feel like it's a best solution. I believe it could be better if one can puts all necessary plugins to the `/plugins` directory, run `docker build` and get everything inside. What do you think about it?

**Comment by juan131** [comment]
Hi @KIVagant 

I agree this is not the best solution. However, there's not an easy way to indicate what plugins should be installed by default. With the current logic, you can:

 * Install it on *app-entrypoint.sh*
 * Install from Admin Panel and persist it for future deployments of your container.

I guess we could indicate what plugins to install on the Image using a environment variable but those plugins should be public ones. @jotadrilo @tompizmor what do you think?

**Comment by KIVagant** [comment]
@juan131 , let me clarify the use case. Maybe anybody else will find it useful too.

I have a plugin that I want to maintain together with a team in the company I'm working for. I tried to use this image as a base to test and develop the plugin. I looked for a repo which could help me to do this without the need to fork and commit anything to Dockerfile. It might be great if for testing goals would be enough to have a `docker-compose` configuration where one can set a directory which will be automatically copied to the plugins directory in the container. I don't think that in's necessary to activate them, this part could be explained in the plugin-related Readme. But it's not cool to have a copy of a Dockerfile from third-party repo in the plugin repo or to have own fork just to have some base Wordpress installed.
If this use case looks interesting for you, I hope to see this ability in the image from Bitnami because I really like your way to do the things. Also, for use case such this, it's important to have ability to use Xdebug. 

As for me, [I found another repo](https://github.com/Keypr/wp-local-docker) that covers my problem (with tiny changes). Nevertheless, thanks for your responses and the cool image.

**Comment by jotadrilo** [comment]
Hi @juan131 @KIVagant 

I don't think we should make this that complicated. We can include the plugins at the very beginning so the scripts initialize WordPress properly:

`Dockerfile.plugins`
```
FROM bitnami/wordpress:latest

ADD plugins /opt/bitnami/wordpress/wp-content/plugins
```

Then, make sure the *plugins* folder contains your desired plugins:

```bash
mkdir plugins
curl -L https://downloads.wordpress.org/plugin/wp-super-cache.1.5.9.zip -o /tmp/wp-super-cache.zip
unzip /tmp/wp-super-cache.zip -d plugins
rm /tmp/wp-super-cache.zip
```

Build the new image:

```
docker build -f Dockerfile.extra -t bitnami/wordpress:plugins .
```

Finally, make sure you use the new image in your deployment:

`docker-compose.yml`
```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress:plugins'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'wordpress_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
```

> *NOTE*: Take a look at the new `image` field for the `wordpress` service

```
docker-compose up -d
```

Now WordPress should include your custom plugins.

I hope it helps!

**Comment by jotadrilo** [comment]
Let me emphasize that building a new image is the proper solution if you are up to use it in production.

If you are developing on top of our image, you could also extend the `docker-compose.yml` configuration by doing this change:

```
...
  wordpress:
    image: 'bitnami/wordpress:4'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'wordpress_data:/bitnami'
      - './plugins/wp-super-cache:/bitnami/wordpress/wp-content/plugins/wp-super-cache'
...
```

> *NOTE*: In this example, I am assuming you have your plugin in the `plugins` folder.

Let us know if this works for your use case!

We understand development should be quick and easy. Thanks for explaining your use case!

**Comment by KIVagant** [comment]
@jotadrilo , thank you!

Looks like when I used "COPY" in the original Dockerfile it didn't work right for me. But in the child Dockerfile it works good!

So, this is my final variant for one plugin:

- Dockerfile:
```
FROM bitnami/wordpress:latest

COPY myplugin.php /opt/bitnami/wordpress/wp-content/plugins/myplugin.php
```

- docker-compose.yaml
```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - './mariadb_data:/bitnami'
    environment:
      - MARIADB_USER=wordpress
      - MARIADB_DATABASE=wordpress
      - MARIADB_PASSWORD=wordpress
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=rootwordpress
      - ALLOW_EMPTY_PASSWORD=no
  wordpress:
    build: ./
    image: 'bitnami/wordpress:plugin'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './wordpress_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=wordpress
      - WORDPRESS_DATABASE_NAME=wordpress
      - WORDPRESS_DATABASE_PASSWORD=wordpress
      - ALLOW_EMPTY_PASSWORD=no
      - WORDPRESS_USERNAME=admin
      - WORDPRESS_PASSWORD=admin
      - WORDPRESS_EMAIL=admin@localhost
      - WORDPRESS_FIRST_NAME=Dev
      - WORDPRESS_LAST_NAME=Test
      - WORDPRESS_BLOG_NAME=My plugin test
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
```

Testing:
```
$ docker-compose build && docker-compose up -d
$ docker exec -it $(docker ps --format "{{.ID}}" --filter="name=wpmyplugin2_wordpress_1") sh
# ls -al /opt/bitnami/wordpress/wp-content/plugins/
total 20
drwxrwxr-x 13 root daemon  416 Feb 27 22:17 .
drwxrwxr-x  5 root daemon  160 Feb 27 22:17 ..
drwxrwxr-x 15 root daemon  480 Feb 27 22:17 akismet
drwxrwxr-x 16 root daemon  512 Feb 27 22:17 all-in-one-seo-pack
drwxrwxr-x 13 root daemon  416 Feb 27 22:17 all-in-one-wp-migration
drwxrwxr-x 10 root daemon  320 Feb 27 22:17 google-analytics-for-wordpress
-rw-rw-r--  1 root daemon 2255 Feb 27 22:17 hello.php
-rw-rw-r--  1 root daemon   28 Feb 27 22:17 index.php
drwxrwxr-x 64 root daemon 2048 Feb 27 22:17 jetpack
drwxrwxr-x 17 root daemon  544 Feb 27 22:17 simple-tags
drwxrwxr-x  7 root daemon  224 Feb 27 22:17 wordpress-mu-domain-mapping
-rw-rw-r--  1 root daemon 9758 Feb 27 22:17 myplugin.php ← this is it!
drwxrwxr-x 10 root daemon  320 Feb 27 22:17 wp-mail-smtp
```
