### ISSUE TITLE
Wordpress DocumentRoot as persistent data

### ISSUE THREAD

**Issue by clemorphy** [bitnami/bitnami-docker-wordpress#135]
Hi

I would expect to find the WordPress DocumentRoot in the host directory while doing :
`volumes:
      - /path/to/wordpress-persistence:/bitnami`

But there are only PHP and Apache conf files in here. Is there a way to access WP DocumentRoot and make those files persistent ?

**Comment by javsalgar** [comment]
Hi, 

The only thing we persist is that of `wp-content` and `wp-config.php`, as otherwise upgrades would not work. Is there a reason why you want to have the whole directory persisted?

**Comment by clemorphy** [comment]
Files of `wp-content` and `wp-config.php` should be enough, but I can't see those files in my WP data persistence directory. Am I missing something ?

**Comment by javsalgar** [comment]
Could you provide a docker-compose file that we can use to reproduce the issue?

**Comment by clemorphy** [comment]
Sure. Here it is :

```
version: '2'

services:
  fix-mariadb-permissions:
    image: 'bitnami/mariadb:latest'
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - /dist/mariadb-persistence:/bitnami
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
    volumes:
      - /dist/mariadb-persistence:/bitnami
  wordpress:
    image: bitnami/wordpress:latest
    depends_on:
      - mariadb
    ports:
      - '80:80'
      - '443:443'
    environment:
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /dist/wordpress-persistence:/bitnami
```

**Comment by carrodher** [comment]
Hi, I am using your `docker-compose.yml` (replacing the path to the persisted volume `/dist/wordpress-persistence` by `/tmp/wordpress-persistence`) and this is the result:
```
$ ls -la /tmp/wordpress-persistence
total 0
drwxr-xr-x   5 crhernandez  wheel  160 Jun 29 09:53 .
drwxrwxrwt  11 root         wheel  352 Jun 29 09:52 ..
drwxr-xr-x   5 crhernandez  wheel  160 Jun 29 09:54 apache
drwxr-xr-x   5 crhernandez  wheel  160 Jun 29 09:54 php
drwxr-xr-x   5 crhernandez  wheel  160 Jun 29 09:54 wordpress

$ ls -la /tmp/wordpress-persistence/wordpress
total 8
drwxr-xr-x  5 crhernandez  wheel   160 Jun 29 09:54 .
drwxr-xr-x  5 crhernandez  wheel   160 Jun 29 09:53 ..
-rw-r--r--  1 crhernandez  wheel     0 Jun 29 09:54 .initialized
-rw-r-----@ 1 crhernandez  wheel  3696 Jun 29 09:54 wp-config.php
drwxrwxr-x@ 5 crhernandez  wheel   160 Jun 29 09:54 wp-content

$ ls -la /tmp/wordpress-persistence/wordpress/wp-content
total 8
drwxrwxr-x@  5 crhernandez  wheel  160 Jun 29 09:54 .
drwxr-xr-x   5 crhernandez  wheel  160 Jun 29 09:54 ..
-rw-rw-r--@  1 crhernandez  wheel   28 Jun 29 09:53 index.php
drwxrwxr-x@ 12 crhernandez  wheel  384 Jun 29 09:53 plugins
drwxrwxr-x@  6 crhernandez  wheel  192 Jun 29 09:54 themes
```

It seems that the persisted data is the expected. Can you try removing volumes?

**Comment by clemorphy** [comment]
After some testing, I have more information.

When I use the docker-compose file I gave you (executing `docker-compose up`), actually nothing appears in the persistence folders. They are just empty.
But WP is working fine.

When I modify the volumes paths, by adding a dot at the beginning, a `mariadb` dir appears in the `mariadb-persistence` folder, and `php` and `apache` dirs appear in the `wordpress-persistence` folder. But Wordpress never finishes its initialization and is not accessible through the browser. And no `wp-content` dir appears.



I am running Docker on Windows 7 with Docker Toolbox.

**Version**

- Output of `docker version`:

```
Client:
 Version:       18.02.0-ce
 API version:   1.36
 Go version:    go1.9.4
 Git commit:    fc4de447b5
 Built: Mon Feb 12 19:03:38 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:20:42 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

- Output of `docker info`:

```
Containers: 7
 Running: 2
 Paused: 0
 Stopped: 5
Images: 20
Server Version: 18.05.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 73
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-boot2docker
Operating System: Boot2Docker 18.05.0-ce (TCL 8.2.1); HEAD : b5d6989 - Thu May 10 16:35:28 UTC 2018
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955GiB
Name: default
ID: O6DS:VPYA:76JW:B6F5:56FV:Y6JC:46O4:6JGO:V7PK:2ULB:7Q3Z:HLGP
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.19.0, build 9e633ef3
docker-py version: 2.7.0
CPython version: 2.7.14
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
```

**Comment by javsalgar** [comment]
Does this issue appear only with this docker-compose file? Are you able to mount any other folders in other containers? Do you have any other docker-compose files that work as expected?

I saw this article, in case it helps: https://rominirani.com/docker-on-windows-mounting-host-directories-d96f3f056a2c

**Comment by clemorphy** [comment]
Mounting host directories works fine with at least an other docker-compose file.

This one : 

```
version: '2'

services:
###########################
# Setup the Apache container
###########################
    httpd:
        container_name: lpe_httpd_1
        restart: always
        image: httpd:2.4.25
        ports:
            - 80:80
        volumes:
            - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./docker/apache/vhosts/:/usr/local/apache2/conf/vhosts
        volumes_from:
            - php

###########################
# Setup the PHP container
###########################
    php:
        container_name: lpe_php_1
        restart: always
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - ./dist/:/usr/local/apache2/htdocs
```

In this one for example, I have access to the documentRoot of the Apache container through my `dist` local directory.


When I don't try to use persistent data, the docker-compose file is working, and WP is running.
When I try to use persistent data with host directories, WP initialization never finishes, apparently because it can't connect to MariaDB : 

`docker-compose up`

```
Creating relationclientenv_fix-mariadb-permissions_1 ... done
Creating network "relationclientenv_default" with the default driver
Creating relationclientenv_mariadb_1                 ... done
Creating relationclientenv_mariadb_1                 ...
Creating relationclientenv_wordpress_1               ... done
Attaching to relationclientenv_fix-mariadb-permissions_1, relationclientenv_mariadb_1, relationclientenv_wordpress_1
fix-mariadb-permissions_1  |
fix-mariadb-permissions_1  | Welcome to the Bitnami mariadb container
fix-mariadb-permissions_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
fix-mariadb-permissions_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
fix-mariadb-permissions_1  |
wordpress_1                |
wordpress_1                | Welcome to the Bitnami wordpress container
wordpress_1                | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
wordpress_1                | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues
wordpress_1                |
relationclientenv_fix-mariadb-permissions_1 exited with code 0
mariadb_1                  |
mariadb_1                  | Welcome to the Bitnami mariadb container
mariadb_1                  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1                  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1                  |
mariadb_1                  | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1                  | nami    INFO  Initializing mariadb
mariadb_1                  | mariadb INFO  ==> Cleaning data dir...
mariadb_1                  | mariadb INFO  ==> Configuring permissions...
mariadb_1                  | mariadb INFO  ==> Validating inputs...
mariadb_1                  | mariadb WARN  Allowing the "rootPassword" input to be empty
mariadb_1                  | mariadb WARN  Allowing the "password" input to be empty
wordpress_1                | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
wordpress_1                | nami    INFO  Initializing apache
wordpress_1                | apache  INFO  ==> Patching httpoxy...
wordpress_1                | nami    INFO  apache successfully initialized
wordpress_1                | nami    INFO  Initializing php
wordpress_1                | nami    INFO  php successfully initialized
wordpress_1                | nami    INFO  Initializing mysql-client
wordpress_1                | nami    INFO  mysql-client successfully initialized
wordpress_1                | nami    INFO  Initializing wordpress
mariadb_1                  | mariadb INFO  ==> Initializing database...
mariadb_1                  | mariadb INFO  ==> Creating 'root' user with unrestricted access...
mariadb_1                  | mariadb INFO  ==> Creating database bitnami_wordpress...
mariadb_1                  | mariadb INFO  ==> Creating user bn_wordpress...
mariadb_1                  | mariadb INFO  ==> Granting access to bn_wordpress to the database bitnami_wordpress...
mariadb_1                  | mariadb INFO
mariadb_1                  | mariadb INFO  ########################################################################
mariadb_1                  | mariadb INFO   Installation parameters for mariadb:
mariadb_1                  | mariadb INFO     Root User: root
mariadb_1                  | mariadb INFO     Root Password: Not set during installation
mariadb_1                  | mariadb INFO     Database: bitnami_wordpress
mariadb_1                  | mariadb INFO     Username: bn_wordpress
mariadb_1                  | mariadb INFO     Password: Not set during installation
mariadb_1                  | mariadb INFO   (Passwords are not shown for security reasons)
mariadb_1                  | mariadb INFO  ########################################################################
mariadb_1                  | mariadb INFO
mariadb_1                  | nami    INFO  mariadb successfully initialized
mariadb_1                  | INFO  ==> Starting mariadb...
mariadb_1                  | INFO  ==> Starting mysqld_safe...
mariadb_1                  | 180709 12:32:09 mysqld_safe Logging to '/opt/bitnami/mariadb/logs/mysqld.log'.
mariadb_1                  | 180709 12:32:09 mysqld_safe Starting mysqld daemon with databases from /opt/bitnami/mariadb/data
relationclientenv_mariadb_1 exited with code 0
wordpress_1                | mysql-c INFO  Trying to connect to MySQL server
wordpress_1                | Error executing 'postInstallation': Failed to connect to mariadb:3306 after 36 tries
relationclientenv_wordpress_1 exited with code 1
```
