### ISSUE TITLE
Custom entrypoint stops bitnami scripts running

### ISSUE THREAD

**Issue by pea** [bitnami/bitnami-docker-wordpress#160]
I'm trying to install cron by creating a Dockerfile and entrypoint, but when it's run bitnami's services aren't started.

It doesn't matter what is in docker-entrypoint.sh - the outcome is the same. I feel like docker-entrypoint.sh is blocking bitnami's entrypoints from running somehow.

Is there a better/ correct way to do this?

Dockerfile:
```
FROM bitnami/wordpress:latest

COPY ./docker-entrypoint.sh /
RUN ["chmod", "+x", "/docker-entrypoint.sh"]
CMD [ "/docker-entrypoint.sh" ] 
```

docker-entrypoint.sh
```
#!/bin/sh

apt-get update
apt-get --assume-yes install cron

service cron start

tail -f /dev/null
```

docker-compose.yaml
```
wordpress:
    build: ./Wordpress
    labels:
      kompose.service.type: nodeport
    ports:
      - "80:80"
    volumes:
      - ./Wordpress/:/bitnami
      - ./Wordpress/cron/:/var/spool/cron
    depends_on:
      - db
    restart: always
    environment:
      MARIADB_HOST: db
      MARIADB_PORT_NUMBER: 3306
      WORDPRESS_DATABASE_USER: wordpress
      WORDPRESS_DATABASE_NAME: wordpress
      WORDPRESS_DATABASE_PASSWORD: wordpress
```
