### ISSUE TITLE
How configuring Wordpress, Drupal, Joomla using same MariaDB container on Bitnami

### ISSUE THREAD

**Issue by plhmk** [bitnami/bitnami-docker-wordpress#168]
Hello,
How can I install Wordpress, Drupal and Joomla in 3 Bitnami containers but using the same container for MariaDB?
I have tried from the Bitnami images of WP, Joomla, Drupal and MariaDB, container installed through Portainer but I can't link the three applications with a single MariaDB database inside Bitnami.
It's possible ?
Can anyone help me configure ENVs?
Thank you and greetings

**Comment by alemorcuq** [comment]
Hi, @plhmk.

You can tell the Wordpress, Drupal and Joomla containers to create the databases themselves. Here's a simple example using a `docker-compose.yml` file:

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress:5'
    ports:
      - '8080:80'
    volumes:
      - 'wordpress_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=bitnami_wordpress
      - MYSQL_CLIENT_CREATE_DATABASE_USER=bn_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  drupal:
    image: 'bitnami/drupal:8'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MYSQL_CLIENT_CREATE_DATABASE_USER=bn_drupal
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=bitnami_drupal
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8081:80'
    volumes:
      - 'drupal_data:/bitnami'
    depends_on:
      - mariadb
  joomla:
    image: 'bitnami/joomla:3'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MYSQL_CLIENT_CREATE_DATABASE_USER=bn_joomla
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=bitnami_joomla
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8082:80'
    volumes:
      - 'joomla_data:/bitnami'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  drupal_data:
    driver: local
  joomla_data:
    driver: local
```

Run `docker-compose up` and you are set. You can find more configuration options in the README files:

https://github.com/bitnami/bitnami-docker-wordpress#create-a-database-for-wordpress-using-mysql-client
https://github.com/bitnami/bitnami-docker-joomla#create-a-database-for-joomla-using-mysql-client
https://github.com/bitnami/bitnami-docker-drupal#create-a-database-for-drupal-using-mysql-client
