### ISSUE TITLE
cURL error 28: Resolving timed out after 3000 milliseconds

### ISSUE THREAD

**Issue by adamczykjac** [bitnami/bitnami-docker-wordpress#184]
I'm using this `docker-compose.yml` description to launch my WP:

```
version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: bn_wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      
  wordpress:
    image: 'wordpress:5.2.2-php7.1-apache'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'wordpress_data:/var/www/html'
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: bn_wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress

volumes:
  wordpress_data:
    driver: local
```

Using the tip from the [image documentation](https://hub.docker.com/_/wordpress) about how to use the WP-CLI, I tried to install the `pl_PL` core language with:

```
docker run -it --rm --volumes-from public-website_wordpress_1 --network container:public-website_wordpress_1 wordpress:cli language core install pl_PL
```
What I get instead of desired output:

```
Error: An unexpected error occurred. Something may be wrong with WordPress.org or this server&#8217;s configuration. If you continue to have problems, please try the <a href="https://wordpress.org/support/">support forums</a>. "cURL error 28: Resolving timed out after 3000 milliseconds"
```
I looked it up [here](https://stackoverflow.com/questions/27776129/php-curl-curlopt-connecttimeout-vs-curlopt-timeout/27776164#27776164) and indeed both of those PHP vars:

* `CURLOPT_TIMEOUT`
* `CURLOPT_CONNECTTIMEOUT`

 are both set to `5` (seconds). I thought adjusting my `docker-compose.yml`accordingly with env var:

```
WORDPRESS_CONFIG_EXTRA: |
        define('CURLOPT_TIMEOUT', 60 );
        define('CURLOPT_CONNECTTIMEOUT', 30 );
```
But this does not seem to have any effect at all, still getting the `"cURL error 28: Resolving timed out after 3000 milliseconds"` message. 

Has any of you any idea why the timeout drops out after those 3000 miliseconds, and not after 5 seconds set in the `CURLOPT_TIMEOUT` and `CURLOPT_CONNECTTIMEOUT` in the config files coming from `wp-includes`?

The host definitely has the firewall set to allow the outgoing connections. Out of the box the `wordpress` image should not have any problems with DNS resolving, am I right (throwing the ideas here only)?

I'm clueless here -.-

**Comment by carrodher** [comment]
Hi, taking a look at the_docker-compose.yaml_, it seems you are not using the [Bitnami WordPress image](https://hub.docker.com/r/bitnami/wordpress). I can show how to do it using the `bitnami/wordpress` image, but unfortunately, I do not know how to solve the issue in another image.

Using this [docker-compose](https://github.com/bitnami/bitnami-docker-wordpress/blob/master/docker-compose.yml) (that is pretty similar to the one you shared above)
```yaml
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    volumes:
      - 'mariadb_data:/bitnami'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress:5'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'wordpress_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
```
you can simply run the following command (once the wordpress container is initialized):
```bash
docker-compose exec wordpress sudo -u daemon -- wp help language core install pl_PL
```

You can find more information about WP-CLI in the [README](https://github.com/bitnami/bitnami-docker-wordpress#wp-cli-tool).

Let's see it working:
- Polski language is not installed:
![Screen Shot 2019-07-12 at 09 05 13](https://user-images.githubusercontent.com/13216600/61109047-34cd0300-a484-11e9-89cf-3e8cca990066.png)
- Execute the WP-CLI command to install it:
```bash
$ docker-compose exec wordpress sudo -u daemon -- wp language core install pl_PL
Warning: Failed to create directory '/usr/sbin/.wp-cli/cache/': mkdir(): Permission denied.
Downloading translation from https://downloads.wordpress.org/translation/core/5.2.2/pl_PL.zip...
Unpacking the update...
Installing the latest version...
Removing the old version of the translation...
Translation updated successfully.
Language 'pl_PL' installed.
Success: Installed 1 of 1 languages.
```
- Polski appears as installed language:
![Screen Shot 2019-07-12 at 08 52 12](https://user-images.githubusercontent.com/13216600/61109048-34cd0300-a484-11e9-99be-09b175314a99.png)

I hope this can help you. If you try to use this image and you find any issues, please feel free to ping us!
