### ISSUE TITLE
wp-staging dir

### ISSUE THREAD

**Issue by stefangweichinger** [bitnami/bitnami-docker-wordpress#185]
I want to mount a persistent volume for exporting backups ("stages") like in:

```
volumes:
      - wp-staging:/wp-staging
```

How to chown that dir so php is able to write to it?

**Comment by marcosbc** [comment]
Hi @stefangweichinger, the Apache service in the container (which executes PHP code via mod_php) is started by the root user, but forks processes to `daemon`. Therefore the proper ownership should be `daemon:daemon`.

**Comment by stefangweichinger** [comment]
Can I set that within docker-compose.yml?

**Comment by marcosbc** [comment]
Hi @stefangweichinger, it is possible to do it in the following way:

    fix-wordpress-volume-ownership:
      image: 'bitnami/wordpress:TAG'
      user: root
      command: chown -R daemon:daemon /wp-staging
      volumes:
        - wp-staging:/wp-staging
    wordpress:
      (...)
      depends_on:
        - fix-mariadb-volume-ownership

Keep in mind that you would need to configure the WordPress application to back up in that specific directory (`/wp-staging`, but I understand you have already covered that).

**Comment by stefangweichinger** [comment]
@marcosbc  thanks for the test and example, will try to build that into my stack.
Yes, the path inside the plugin is set manually for now, I also asked the author to let me store it in the DB ;-)

**Comment by stefangweichinger** [comment]
minor feedback: your example isn't fully ok.

the depends_on clause should say

```
depends_on:
    - fix-wordpress-volume-ownership
```

right?

I try to copy that, so far it fails for me, I will check back with details.

**Comment by stefangweichinger** [comment]
I post my whole compose file for reference, ok? anonymized, sure.

```
# cat docker-compose.yml 
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mariadb_data:/bitnami
  wordpress:
    image: bitnami/wordpress:latest
    depends_on:
      - mariadb
      - fix-wordpress-volume-ownership
    #ports:
      #- '9182:80'
        #- '9143:443'
    environment:
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=someUser
      - SMTP_PASSWORD=somePassword
      - SMTP_PROTOCOL=tls
    volumes:
      - wordpress_data:/bitnami
      - wp-staging:/wp-staging
      - ./fonts:/opt/bitnami/wordpress/wp-includes/fonts
  varnish:
    build:
      context: ./custom-varnish
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    restart: always
    ports:
      - 9180:6081
    environment:
      BACKENDS: "wordpress"
      BACKENDS_PORT: 80
      BACKENDS_PROBE_ENABLED: "false"
    logging:
      options:
        max-size: 10m

  fix-wordpress-volume-ownership:
    image: 'bitnami/wordpress:latest'
    user: root
    command: 
      - chown -R daemon:daemon /wp-staging
      - chown -R daemon:daemon /opt/bitnami/wordpress
    volumes:
      - wp-staging:/wp-staging

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  wp-staging:
    driver: local
```

docker-compose shows that fix-container failing:

```
fix-wordpress-volume-ownership_1  | [FATAL tini (11)] exec chown -R daemon:daemon /wp-staging failed: No such file or directory
```

Maybe my 2 commands are formatted wrong, although the message seems to be clear here.
I don't see my typo or so ...
