### ISSUE TITLE
special commands problem

### ISSUE THREAD

**Issue by mokerosan** [bitnami/bitnami-docker-wordpress#190]
How can I execute these commands on my stack so that they remain after the image is restarted?

```bash
sudo touch /opt/bitnami/wordpress/.htaccess
sudo chown bitnami:daemon /opt/bitnami/wordpress/.htaccess
sudo chmod g+w /opt/bitnami/wordpress/.htaccess
sudo chown -R bitnami:daemon /opt/bitnami/wordpress/wp-content/cache
sudo find /opt/bitnami/wordpress/wp-content/cache -type f -exec chmod 664 {} \;
sudo find /opt/bitnami/wordpress/wp-content/cache -type d -exec chmod 775 {} \;
sudo chown bitnami:daemon /opt/bitnami/wordpress/wp-config.php
sudo chmod g+w /opt/bitnami/wordpress/wp-config.php
```
my actual stack
```yaml
version: '3.3'
services:
  mariadb:
    image: bitnami/mariadb:10.3
    environment:
     - MARIADB_USER=bn_wordpress
     - MARIADB_DATABASE=bitnami_wordpress
     - ALLOW_EMPTY_PASSWORD=yes
    volumes:
     - mariadb_data4:/bitnami
    networks:
     - default
    logging:
      driver: json-file
  wordpress:
    image: bitnami/wordpress:5
    environment:
     - MARIADB_HOST=mariadb
     - MARIADB_PORT_NUMBER=3306
     - WORDPRESS_DATABASE_USER=bn_wordpress
     - WORDPRESS_DATABASE_NAME=bitnami_wordpress
     - ALLOW_EMPTY_PASSWORD=yes
    ports:
     - 8002:80
    volumes:
     - wordpress_data3:/opt/bitnami/wordpress
    networks:
     - default
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.tags: traefik-public
        traefik.redirectorservice.frontend.redirect.entryPoint: https
        traefik.webservice.frontend.entryPoints: https
        traefik.redirectorservice.frontend.entryPoints: http
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.port: '80'
        traefik.frontend.rule: Host:blog1.example.com
networks:
  default:
    driver: overlay
  traefik-public:
    external: true
volumes:
  wordpress_data3:
    driver: local
  mariadb_data4:
    driver: local
```
