### ISSUE TITLE
multisite problem

### ISSUE THREAD

**Issue by mokerosan** [bitnami/bitnami-docker-wordpress#191]
I need to activate multisite, but when it asks me to add parameters in the .htaccess I only find this file "wordpress-htaccess.conf" in the folder "/opt/bitnami/wordpress". the bad thing is that this file is not mounted so when the container restarts it loses its configuration.

so my question is if this file is the .htaccess that my container recognizes and the other is knowing how to mount this file so that it does not lose its configuration to restart

![image](https://user-images.githubusercontent.com/31668345/63816822-9697de00-c907-11e9-92f3-21b6e2b4bb43.png)

Thanks!

my stack
```
version: '3.3'
services:
  mariadb:
    image: bitnami/mariadb:10.3
    environment:
     - MARIADB_USER=bn_wordpress
     - MARIADB_DATABASE=bitnami_wordpress
     - ALLOW_EMPTY_PASSWORD=yes
    volumes:
     - mariadb_data4:/bitnami
    networks:
     - default
    logging:
      driver: json-file
  wordpress:
    image: bitnami/wordpress:5
    environment:
     - MARIADB_HOST=mariadb
     - MARIADB_PORT_NUMBER=3306
     - WORDPRESS_DATABASE_USER=bn_wordpress
     - WORDPRESS_DATABASE_NAME=bitnami_wordpress
     - ALLOW_EMPTY_PASSWORD=yes
    ports:
     - 8002:80
    volumes:
     - wordpress_data3:/bitnami
    networks:
     - default
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.tags: traefik-public
        traefik.redirectorservice.frontend.redirect.entryPoint: https
        traefik.webservice.frontend.entryPoints: https
        traefik.redirectorservice.frontend.entryPoints: http
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.port: '80'
        traefik.frontend.rule: Host:blog1.example.com
networks:
  default:
    driver: overlay
  traefik-public:
    external: true
volumes:
  wordpress_data3:
    driver: local
  mariadb_data4:
    driver: local
```
