### ISSUE TITLE
Error executing 'postInstallation': File '/opt/bitnami/php/conf/php.ini' does not exists

### ISSUE THREAD

**Issue by gustavo-a** [bitnami/bitnami-docker-wordpress#193]
**Description**

Whenever I try to create and start my containers I get this error. I am mounting volumes on apache and php folders. My guess is that this is causing the issue.

**My `docker-compose` file**

```
version: '3'

services:
  mysql:
    container_name: ${PROJECT_NAME}_mysql
    image: mariadb
    volumes:
      - database:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpback

  wordpress:
    container_name: ${PROJECT_NAME}_wp
    depends_on:
      - mysql
    image: bitnami/wordpress:latest
    restart: always
    volumes:
      - ./wp:/bitnami/wordpress
      - ./config/apache:/opt/bitnami/apache/conf
      - ./config/php:/opt/bitnami/php/conf
    environment:
      VIRTUAL_HOST: ${PROJECT_NAME}.local
      VIRTUAL_PORT: 80
      MARIADB_HOST: mysql
      MARIADB_PORT_NUMBER: 3306
      WORDPRESS_DATABASE_NAME: wordpress
      WORDPRESS_DATABASE_USER: wordpress
      WORDPRESS_DATABASE_PASSWORD: wordpress
      WORDPRESS_USERNAME: admin
      WORDPRESS_PASSWORD: admin
      WORDPRESS_EMAIL: admin@admin.local
      WORDPRESS_BLOG_NAME: I love Docker!
    networks:
      - wpback
      - wpfront

networks:
  wpback:
  wpfront:
    external:
      name: proxy
volumes:
  database:
```

**Steps to reproduce the issue:**

1. Set up your `docker-compose` file and mount volumes on apahe and php folders like this
```
volumes:
      - ./wp:/bitnami/wordpress
      - ./config/apache:/opt/bitnami/apache/conf
      - ./config/php:/opt/bitnami/php/conf
```
2. Run `docker-compose up -d`

**Describe the results you received:**

All containers are running, except the wordpress container.
I got this on the logs:

```
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing wordpress
Error executing 'postInstallation': File '/opt/bitnami/php/conf/php.ini' does not exists
```

**Expected resuts:**

The containers should be up and running

**Version**

- Output of `docker version`:

```
Docker version 19.03.2, build 6a30dfca03
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 7
  Running: 7
  Paused: 0
  Stopped: 0
 Images: 56
 Server Version: 19.03.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.0.0-27-generic
 Operating System: Ubuntu 19.04
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.682GiB
 Name: gustavo-Lenovo-G40-70
 ID: SMZJ:BD45:U44K:AZMM:4PD5:FS4Y:ZQQI:Z4TL:SD6U:5S3D:Z7T3:KU4J
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version`:

```
docker-compose version 1.21.0, build unknown
docker-py version: 3.4.1
CPython version: 3.7.3
OpenSSL version: OpenSSL 1.1.1b  26 Feb 2019
```
