### ISSUE TITLE
Container WordPress closes without error message (Docker, Bitnami, MySQL)

### ISSUE THREAD

**Issue by DuerrundSteidle** [bitnami/bitnami-docker-wordpress#200]
Hello together,

I have a problem creating containers. I want to use the console to create containers automatically. This works so far only it stops the container WordPress after a short time.

I guess the problem is related to MySQl because the automatic creation with MariaDB already worked. But with MySQL I can't get it to work.

The Container WordPress closes without any error message. The only message I got in Synology is that it closes. ( It is shown in the picture)

Would be great if someone could help me.

Greetings

```
version: '3.7'
  services:
  db:
    image: bitnami/mysql:latest
    volumes:
      - ./db
    environment:
      - MYSQL_ROOT_PASSWORD=duerrundsteidle
      - MYSQL_DATABASE=duerrundsteidle
      - MYSQL_USER=duerrundsteidle
      - MYSQL_PASSWORD=duerrundsteidle
  wordpress:
    image: bitnami/wordpress:latest
    depends_on:
      - db
    ports:
      - 8000:80
      - 4000:443
    volumes:
      - ./wordpress
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=wpdb
      - WORDPRESS_DB_USER=user
      - WORDPRESS_DB_PASSWORD=passowrd
  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - 12000:80
      - 14000:443
    volumes:
      - ./phpmyadmin
```

**Comment by juan131** [comment]
Hi @DuerrundSteidle 

Thanks for reporting this issue. Some users reported the same issue in the repository below:

- https://github.com/bitnami-labs/aci-templates/issues/6

I guess you're facing an error like the one below in the WordPress logs:

```
Error executing 'postInstallation': Cannot connect to MySQL server:
MySQL command failed to run. Error: 
 ERROR 1156 (08S01): Plugin caching_sha2_password could not be loaded: /opt/bitnami/mysql//opt/bitnami/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory
```

It looks like we introduced some incompatibility with MySQL at some point in the MySQL client used in the WordPress image, and it's only compatible with MariaDB. 

We didn't notice it since we're testing this image with MariaDB in our daily tests. I created a task to investigate what's going on but we didn't have time to work on it yet. In the meantime, we recommend you to use the `bitnami/mariadb` image instead.

**Comment by DuerrundSteidle** [comment]
Ok thanks for your very fast answer.

I think also it could be the same problem.

I will try to test the suggestion and looking forward to here from you when you solved the problem.

**Comment by sameersbn** [comment]
@DuerrundSteidle Please note if using MariaDB is not an option, you could switch to the `bitnami/mysql:5.7` image

```yaml
version: '3.7'
services:
  db:
    image: bitnami/mysql:5.7
    volumes:
      - ./db
    environment:
      - MYSQL_ROOT_PASSWORD=duerrundsteidle
      - MYSQL_DATABASE=duerrundsteidle
      - MYSQL_USER=duerrundsteidle
      - MYSQL_PASSWORD=duerrundsteidle
  wordpress:
    image: bitnami/wordpress:latest
    depends_on:
      - db
    ports:
      - 8000:80
      - 4000:443
    volumes:
      - ./wordpress
    environment:
      - MARIADB_HOST=db
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=duerrundsteidle
      - WORDPRESS_DATABASE_USER=duerrundsteidle
      - WORDPRESS_DATABASE_NAME=duerrundsteidle
      - WORDPRESS_DATABASE_PASSWORD=duerrundsteidle
  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - 12000:80
      - 14000:443
    volumes:
      - ./phpmyadmin
```

**Comment by sameersbn** [comment]
@DuerrundSteidle you may also want to take a look at my comment here https://github.com/bitnami-labs/aci-templates/issues/6#issuecomment-571070834

**Comment by DuerrundSteidle** [comment]
Thanks for your answer I've tested it with the following code. And in the picture you can see the occured error.

[URL=https://www.bilder-upload.eu/bild-66ed72-1578512537.png.html](url)

version: '3.7'
services:
  db:
    image: bitnami/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=duerrundsteidle
      - MYSQL_DATABASE=duerrundsteidle
      - MYSQL_USER=duerrundsteidle
      - MYSQL_PASSWORD=duerrundsteidle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./db
  wordpress:
    image: bitnami/wordpress:latest
    depends_on:
     - db
    ports:
      - 8000:80
      - 4000:443
    environment:
      - MARIADB_HOST=db
      - MARIA_PORT_NUMBER=3306
      - MARIA_PORT_USER=root
      - MARIA_ROOT_PASSWORD=duerrundsteidle
      - WORDPRESS_DB_NAME=duerrundsteidle
      - WORDPRESS_DB_USER=duerrundsteidle
      - WORDPRESS_DB_PASSWORD=duerrundsteidle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./wordpress
  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - 12000:80
      - 14000:443
    volumes:
      - ./phpmyadmin

**Comment by juan131** [comment]
I couldn't access the image @DuerrundSteidle 

Regarding your **docker-compose.yaml**, I'm missing the section @sameersbn suggested:

```yaml
    volumes:
      - 'mysql_data:/bitnami/mysql'
      - '/path/to/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro'
```

You're not mounting any custom MySql config file with the piece of configuration below:

```
[mysqld]
default_authentication_plugin=mysql_native_password
```

**Comment by DuerrundSteidle** [comment]
[FirstError](https://www.bilder-upload.eu/bild-66ed72-1578512537.png.html)
Sry here is the picture again

Now I do what is written in this task
[Task](https://www.akamenskiy.com/fix-wordpress-database-connection-mysql-8/)

Now the following Error occured
[LastError](https://www.bilder-upload.eu/bild-69d77e-1578667659.png.html)

Could it be possible that I'm in the wrong folder?

Here is my code

```
version: '3.7'
services:
  mysql:
    image: bitnami/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=duerrundsteidle
      - MYSQL_DATABASE=duerrundsteidle
      - MYSQL_USER=duerrundsteidle
      - MYSQL_PASSWORD=duerrundsteidle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ' mysql_data:/bitnami/mysql'
      - '/path/to/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro'
  wordpress:
    image: bitnami/wordpress:latest
    depends_on:
     - mysql
    ports:
      - 8000:80
      - 4000:443
    environment:
      - MARIADB_HOST=mysql
      - MARIA_PORT_NUMBER=3306
      - MARIA_PORT_USER=root
      - MARIA_ROOT_PASSWORD=duerrundsteidle
      - WORDPRESS_DB_NAME=duerrundsteidle
      - WORDPRESS_DB_USER=duerrundsteidle
      - WORDPRESS_DB_PASSWORD=duerrundsteidle
      - WORDPRESS_SCHEME=https
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./wordpress
  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    depends_on:
      - mysql
    ports:
      - 12000:80
      - 14000:443
    volumes:
      - ./phpmyadmin
```

**Comment by DuerrundSteidle** [comment]
Additional I couldnt find any folder in opt is this normal?

[Folder](https://www.bilder-upload.eu/bild-8e79c4-1578668299.png.html)

**Comment by juan131** [comment]
Hi @DuerrundSteidle 

The error you faced is related to your volumes structure. You added the piece below:

```yaml
services:
  mysql:
  ...
    volumes:
      - 'mysql_data:/bitnami/mysql'
```

However, you did not define the `mysql_data` volume. 

You have two options. Mount a local directory as you did for WordPress or PhpMyAdmin, or define the corresponding volume adding the block below at the end of your **docker-compose.yaml** (check how it's done at https://github.com/bitnami/bitnami-docker-wordpress/blob/master/docker-compose.yml):

```yaml
volumes:
  mariadb_data:
    driver: local
```
