### ISSUE TITLE
Database access and site name help.

### ISSUE THREAD

**Issue by cthom-dev** [bitnami/bitnami-docker-wordpress#202]
I have a working wordpress installation on localhost, but the only way I can currently access the local mariadb is through phpmyadmin. Is there a way to use Sequel Pro or TablePlus in local dev?

Also I would like to setup a custom domain for in my local dev environment, such as project.local or project.test instead of using localhost. The docs say `The Apache configuration volume (/bitnami/apache) has been deprecated, and support for this feature will be dropped in the near future. ` So what is the best way to achieve this?

Thanks.

**docker-compose.yml**

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    volumes:
      - '~/Docker/someproject/docker_volume/mariadb_data:/bitnami'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress:5'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '~/Docker/someproject/docker_volume/wordpress_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_SCHEME=https
      - ALLOW_EMPTY_PASSWORD=yes
  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    depends_on:
      - mariadb
    ports:
      - '8080:80'
      - '4843:443'
    volumes:
      - ~/Docker/someproject/docker_volume/phpmyadmin_data:/bitnami
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  phpmyadmin_data:
    driver: local
 ```

**Version**

- Output of `docker version`:

```
Docker version 19.03.5, build 633a0ea
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 1.943GiB
 Name: docker-desktop
 ID: JO4Y:EARG:J2TP:W7WC:ETR7:3CEC:BMQK:SCOG:PJRG:HMVD:ZOFB:74N5
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 58
  Goroutines: 70
  System Time: 2020-01-24T01:23:07.1422976Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine```
