### ISSUE TITLE
WordPress stuck at "Starting wordpress..."

### ISSUE THREAD

**Issue by rizkysyazuli** [bitnami/bitnami-docker-wordpress#217]
**Description**

The WordPress service stuck at this step:

    wordpress_1  | INFO  ==> Starting wordpress...

I'm using Bitnami's WordPress and MariaDB as a backend service, and an [Ember JS](https://hub.docker.com/r/danlynn/ember-cli/) app as the frontend.

Everything was running fine before. But then out of nowhere, my frontend service failed to start due to some unknown JS error. So i decided to do a fresh start.

**Steps to reproduce the issue:**

1. Ran `docker-compose down -v --rmi all`.
2. Fire up `docker-compose up` again.

**Describe the results you received:**

The WordPress container stuck as described above.

**Additional information you deem important:**

My docker-compose.yml file.

```yml
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    ports:
      - '3307:3306'
    volumes:
      - '.:/bitnami:delegated'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress:5'
    ports:
      - '8080:80'
      - '883:443'
    volumes:
      - '.:/bitnami:delegated'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  ember:
    image: danlynn/ember-cli:3.14.0
    volumes:
      - '.:/myapp:consistent'
      - '.bash_history:/root/.bash_history:cached'
      - 'node_modules:/myapp/node_modules:cached'
    tmpfs:
      - '/myapp/tmp'
    ports:
      - '4200:4200'
      - '7020:7020'
      - '7357:7357'
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  node_modules:

```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 8
  Running: 3
  Paused: 0
  Stopped: 5
 Images: 11
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.846GiB
 Name: docker-desktop
 ID: EI5M:2DVI:4FX3:N72O:UO7T:IUHO:ZFOI:6SPX:V37Q:6EWA:R5YZ:MYH7
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 61
  Goroutines: 86
  System Time: 2020-02-28T20:20:10.472622442Z
  EventsListeners: 4
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Using Docker for Mac
