### ISSUE TITLE
mysql-c INFO  Trying to connect to MySQL server

### ISSUE THREAD

**Issue by polRk** [bitnami/bitnami-docker-wordpress#226]
Similar to #88 .
deployment stoped and output
`mysql-c INFO  Trying to connect to MySQL server`

After that, I deleted the volumes Directive in docker-compose services.WordPress, and everything worked.
```
    volumes:
#      - './wordpress:/bitnami/wordpress'
```

**Comment by polRk** [comment]
The problem is **.initialized** file. After deleting everything goes smoothly

**Comment by andresbono** [comment]
Hi @polRk, is your issue solved already?

Let us know if we can help with anything.

**Comment by polRk** [comment]
No, after recreating the pod , by running `docker-compose up -d`, I see `mysql-c INFO Trying to connect to MySQL server` and then, throw an error. But if i **.initialized file** wordpress starts initializing and filling the wp-content folder with garbage files

**Comment by andresbono** [comment]
Can you give us the link to the docker-compose file that you are using?

Can you also make sure that you are using the latest version of the container images?

**Comment by polRk** [comment]
> Can you also make sure that you are using the latest version of the container images?

Yes!

> Can you give us the link to the docker-compose file that you are using?

Oh, no, i just use docker wordpress image
```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress:5'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - './wordpress/wp-content:/bitnami/wordpress/wp-content'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mariadb_data:
    driver: local
```

You can try to reproduce by running docker-compose up => docker-compose down => dcoker-compose up

**Comment by andresbono** [comment]
We couldn't reproduce the issue, @polRk.

Can you think of any peculiarity of the file system where you are mounting the `./wordpress` directory? Can that be the cause of the issue?

We tried both

```
volumes:
      - './wordpress/wp-content:/bitnami/wordpress/wp-content'
```

and

```
volumes:
      - './wordpress:/bitnami/wordpress'
```

Being the last one the recommended to ensure WordPress is working correctly. See 

https://github.com/bitnami/bitnami-docker-wordpress/blob/f353722fe84a3fdfabc8171ffcb07da6dc26cc8e/5/debian-10/docker-compose.yml#L16-L17

**Comment by polRk** [comment]
I have problem , i need my wp-content with real-time updates. I edit files in my wp-content => update browser tab => see changes

**Comment by andresbono** [comment]
Maybe you can try to mount two volumes:

```
  wordpress:
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
      - './wordpress/wp-content:/bitnami/wordpress/wp-content'

volumes:
  wordpress_data:
    driver: local
```

It may help to resolve your issues.
