### ISSUE TITLE
Support for IPv6 in Apache config

### ISSUE THREAD

**Issue by anuragbhatia** [bitnami/bitnami-docker-wordpress#253]
Just brought up a setup with IPv6 with the latest image. I defined IPv4 and IPv6 address in docker-compose and container picked up it fine. Though I see it's listening only on IPv4:8080 and not IPv6:8080. 

Please consider adding support for iPv6 in Apache config. 

Docker version
```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:22 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:10:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by carrodher** [comment]
Hi, thanks for reporting this issue. In order to be able to reproduce the issue and provide more information if it is needed to implement any changes, can you please share with us the changes you are doing in the docker-compose to enable IPv6? Thanks

**Comment by anuragbhatia** [comment]
Hi sure, 

Please find my docker-compose file excluding environment:

```
version: '2'
services:
  mariadb:
    container_name: anuragbhatia.com_db
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    volumes:
      - 'anuragbhatia.com-mariadb_data:/bitnami/mariadb'
    environment:
_**(excluded)**_

    networks:
      backend:           
    restart: always     

  wordpress:
    container_name: anuragbhatia.com_wp
    image: 'docker.io/bitnami/wordpress:5-debian-10'
    # ports:
      # - '80:8080'
      # - '443:8443'
    volumes:
      - 'anuragbhatia.com-wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
_**(excluded)**_

    networks:
      01dockernet:
              ipv4_address: 10.20.72.12
              ipv6_address: 2402:b580:1:72::12
      backend:         
    restart: always     


volumes:
  anuragbhatia.com-mariadb_data:
    # driver: local
    external: true

  anuragbhatia.com-wordpress_data:
    # driver: local
    external: true

networks:
  01dockernet:
      external: true    
  backend:    
```
