### ISSUE TITLE
Can't mount external httpd.conf file.

### ISSUE THREAD

**Issue by kriptor** [bitnami/bitnami-docker-wordpress#269]
**Description**

I'm using bitnami wordpress helm chart which seems to be using this docker image.
I created a ConfigMap _wordpress-httpd_ which contains key _httpd.conf_ with the value of my own httpd config.

Then I specified the following values of the helm chart:
```
extraVolumes:
  - name: wordpress-httpd
    configMap:
      name: wordpress-httpd
      items:
        - key: "httpd.conf"
          path: "httpd.conf"
extraVolumeMounts:
  - name: wordpress-httpd
    mountPath: /opt/bitnami/apache/conf/httpd.conf
    subPath: httpd.conf
    readOnly: false
```

and when I try to apply, it fails with the following log:
```
wordpress 
wordpress Welcome to the Bitnami wordpress container
wordpress Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
wordpress Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues
wordpress 
wordpress nami    INFO  Initializing apache
wordpress Error executing 'postInstallation': EROFS: read-only file system, open '/opt/bitnami/apache/conf/httpd.conf'
wordpress stream closed
```

I don't expect this _httpd.conf_ of mine to be changed in any way so I'm not really sure what is the problem and would appreciate some help.

**Steps to reproduce the issue:**

See description above.

**Describe the results you received:**

See description above.

**Describe the results you expected:**

See description above.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

Helm chart **bitnami/wordpress v9.8.2** which uses **bitnami/wordpress:5.5.1-debian-10-r58**

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by dani8art** [comment]
Hi @kriptor, thanks for opening this issue, we can confirm that is happening. When we mount a ConfigMap in kubernete it is mounted in a read-only file system and the `bitnami/wordpress` image performs some write operations to this file in order to configure the apache instance. This would be something that we need to improve and permit users to mount their own `httpd.conf` directly.

As a workaround, you will need to mount this file in another location and add an init container that cp/mv the file to the proper location something like:

```yaml
initContainers: |-
  - name: your-image-name
     image: bitnami/minideb
     imagePullPolicy: IfNotPresent
     command: ['sh', '-c', 'cp /bitnami/wordpress/custom/httpd.conf /opt/bitnami/apache/conf/httpd.conf']
     volumeMounts: {{- include "wordpress.tplValue" (dict "value" .Values. extraVolumeMounts "context" $) | nindent 4 -}}
```
