### ISSUE TITLE
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/wordpress/wp-content'

### ISSUE THREAD

**Issue by talktolanka** [bitnami/bitnami-docker-wordpress#273]
Hi,
I want to do the deployment with the UUID 1001. But I am getting permission issue.
Below is my deployment script. Note: I have added a initContainer - but no any luck

```
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: wp-pod
  name: wp-pod
  namespace: default
spec:
  initContainers:
  - name: "busy"
    image: "busybox"
    command: ["sh", "-c", "mkdir -p /bitnami/wordpress && chown 1001:root -R /bitnami/wordpress"]
  containers:
  - env:
    - name: ALLOW_EMPTY_PASSWORD
      value: "no"
    - name: MARIADB_HOST
      value: x.y.x.a
    - name: MARIADB_PORT_NUMBER
      value: "3306"
    - name: WORDPRESS_DATABASE_NAME
      value: user023_DB
    - name: WORDPRESS_DATABASE_USER
      value: user023
    - name: WORDPRESS_DATABASE_PASSWORD
      value: mypassword
    - name: WORDPRESS_USERNAME
      value: user023
    - name: WORDPRESS_PASSWORD
      value: mypassword
    - name: WORDPRESS_EMAIL
      value: myemail@gmail.com
    - name: WORDPRESS_FIRST_NAME
      value: FirstName
    - name: WORDPRESS_LAST_NAME
      value: LastName
    - name: WORDPRESS_HTACCESS_OVERRIDE_NONE
      value: "no"
    - name: WORDPRESS_HTACCESS_PERSISTENCE_ENABLED
      value: "no"
    - name: WORDPRESS_BLOG_NAME
      value: User's Blog!
    - name: WORDPRESS_SKIP_INSTALL
      value: "no"
    - name: WORDPRESS_TABLE_PREFIX
      value: wptest_
    - name: WORDPRESS_SCHEME
      value: http
    - name: WORDPRESS_EXTRA_WP_CONFIG_CONTENT
    image: docker.io/bitnami/wordpress:5-debian-10
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 6
      httpGet:
        path: /wp-admin/install.php
        port: http
        scheme: HTTP
      initialDelaySeconds: 120
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: wordpress
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    - containerPort: 8443
      name: https
      protocol: TCP
    readinessProbe:
      failureThreshold: 6
      httpGet:
        path: /wp-login.php
        port: http
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      requests:
        cpu: 300m
        memory: 512Mi
    securityContext:
      runAsUser: 1001
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /bitnami/wordpress
      name: wordpress-data
      subPath: wordpress
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-k88gm
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  volumes:
  - name: wordpress-data
    persistentVolumeClaim:
      claimName: gcp-nfs
  - name: default-token-k88gm
    secret:
      defaultMode: 420
      secretName: default-token-k88gm
```

When I check the logs I get following result

> nami    INFO  Initializing apache
> nami    INFO  apache successfully initialized
> nami    INFO  Initializing mysql-client
> nami    INFO  mysql-client successfully initialized
> nami    INFO  Initializing wordpress
> wordpre INFO  ==> Preparing Varnish environment
> wordpre INFO  ==> Preparing Apache environment
> wordpre INFO  ==> Preparing PHP environment
> mysql-c INFO  Trying to connect to MySQL server
> mysql-c INFO  Found MySQL server listening at a.b.c.d:3306
> mysql-c INFO  MySQL server listening and working at a.b.c.d:3306
> wordpre INFO  Preparing WordPress environment
> Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/wordpress/wp-content'

Please help me to come out of this error. I really want to deploy this with UUID 1001

Thanks

**Comment by airmonitor** [comment]
Hello.

Worked for me with below

WORDPRESS_RESET_DATA_PERMISSIONS=yes

**Comment by talktolanka** [comment]
Hi Thanks for the reply. But still I am getting the same issue.  Now I get the error

Error executing 'postInstallation': EPERM: operation not permitted, utime '/bitnami/wordpress/.restored'

Please share  a working definitions yaml if you have.

**Comment by airmonitor** [comment]
Sure,

I'm using AWS ECS with this container

        container = task.add_container(
            "container",
            environment={
                "WORDPRESS_RESET_DATA_PERMISSIONS": "yes",
                "WORDPRESS_SKIP_INSTALL": props["wordpress_skip_install"],
                "AWS_ALB_URL": os.environ.setdefault("AWS_ALB_URL", ""),
            },
            essential=True,
            image=ecs.ContainerImage.from_docker_image_asset(wordpress_docker_image),
            logging=ecs.AwsLogDriver(stream_prefix="container", log_group=container_log_group),
            readonly_root_filesystem=False,
            secrets={
                "MARIADB_HOST": Secret.from_secrets_manager(db_secret, "host"),
                "MARIADB_ROOT_PASSWORD": Secret.from_secrets_manager(db_secret, "password"),
                "MARIADB_ROOT_USER": Secret.from_secrets_manager(db_secret, "username"),
                "WORDPRESS_DATABASE_NAME": Secret.from_secrets_manager(db_secret, "dbname"),
                "WORDPRESS_DATABASE_PASSWORD": Secret.from_secrets_manager(db_secret, "password"),
                "WORDPRESS_DATABASE_USER": Secret.from_secrets_manager(db_secret, "username"),
                "WORDPRESS_PASSWORD": Secret.from_secrets_manager(db_secret, "password"),
                "WORDPRESS_USERNAME": Secret.from_secrets_manager(db_secret, "username"),
            },
        )

the rest env's are not changed.

**Comment by talktolanka** [comment]
No luck!!! So strange. Below is my working definition with  **runAsUser: 0** change. I also clean my code for you reference below

---
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: wp-pod
  name: wp-pod
  namespace: default
spec:
  containers:
  - env:
    - name: WORDPRESS_RESET_DATA_PERMISSIONS
      value: "yes"
    - name: ALLOW_EMPTY_PASSWORD
      value: "no"
    - name: MARIADB_HOST
      value: a.b.c.d
    - name: MARIADB_PORT_NUMBER
      value: "3306"
    - name: WORDPRESS_DATABASE_NAME
      value: user023_DB
    - name: WORDPRESS_DATABASE_USER
      value: user023
    - name: WORDPRESS_DATABASE_PASSWORD
      value: ADlylmg8DitB
    - name: WORDPRESS_USERNAME
      value: user023
    - name: WORDPRESS_PASSWORD
      value: ADlylmg8Di
    - name: WORDPRESS_EMAIL
      value: myemail@gmail.com
    - name: WORDPRESS_FIRST_NAME
      value: FirstName
    - name: WORDPRESS_LAST_NAME
      value: LastName
    - name: WORDPRESS_HTACCESS_OVERRIDE_NONE
      value: "no"
    - name: WORDPRESS_HTACCESS_PERSISTENCE_ENABLED
      value: "no"
    - name: WORDPRESS_BLOG_NAME
      value: User's Blog!
    - name: WORDPRESS_SKIP_INSTALL
      value: "no"
    - name: WORDPRESS_TABLE_PREFIX
      value: wptest_
    - name: WORDPRESS_SCHEME
      value: http
    - name: WORDPRESS_EXTRA_WP_CONFIG_CONTENT
    image: docker.io/bitnami/wordpress:5.5.3-debian-10-r31
    imagePullPolicy: IfNotPresent
    securityContext:
     runAsUser: 0
    name: wordpress
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    - containerPort: 8443
      name: https
      protocol: TCP
    volumeMounts:
    - mountPath: /bitnami/wordpress
      name: wordpress-data
      subPath: wordpress
  volumes:
  - name: wordpress-data
    persistentVolumeClaim:
      claimName: gcp-nfs

```

1. Above definition working fine, so that I know NFS and MySQL connectivity are OK
2. Then when I  change the **runAsUser to 1001**,  below error popping.

`**_Error executing 'postInstallation': EPERM: operation not permitted, utime '/bitnami/wordpress/.restored'_**`

3. Are you running the definition with **runAsUser: 1001**  also are you running a **initContainer** to solve the permission issue. If so please share the initContainer details.

4. Also I have changed the image to **5.5.3-debian-10-r31.** Hope your have the same or recent.

If you can give these information would help to solve the issue.  

Thanks for your help
