### ISSUE TITLE
Issue with direct-update Wordpress - SYNOLOGY DSM

### ISSUE THREAD

**Issue by ansred** [bitnami/bitnami-docker-wordpress#274]
**Description**

Issue updating directly wordpress

![image](https://user-images.githubusercontent.com/5244872/102023858-375c1800-3d5c-11eb-8751-8d1ea9152449.png)

**Describe the results you received:**

Update failed 

**Describe the results you expected:**

That should be able to update directly

**Version**

Latest image used:

https://registry.hub.docker.com/r/bitnami/wordpress/
```

- Output of `docker-compose version` (if applicable):

```

`version: '2.1'

services:

  wordpress:
    image: wordpress:latest
    restart: unless-stopped
    ports:
      - 8789:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ansred
      WORDPRESS_DB_PASSWORD: db123123
      WORDPRESS_DB_NAME: fooddb
    volumes:
      - /volume1/docker/WordPress/food/config/data:/var/www/html
    links:
      - db:db

  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: fooddb
      MYSQL_USER: ansred
      MYSQL_PASSWORD: db123123
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:`

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Docker Host: Synology DSM



Maybe If I can specify PUID and PGID as root 0 and 0? should fix  the issue?

If yes, where should I add them in the docker compose above?

**Comment by javsalgar** [comment]
Hi,

The issue seems to be because of lack of permissions of the non-root container in your volume folder. Is there a way you can chmod to add more permissions in your Synology volume folder? If not, you may need to change the container to use `user: root` (it's a line in the wordpress container section in the docker-compose file).

**Comment by ansred** [comment]
@javsalgar I managed to get it working by tweaking the docker compose as the following

Things are working fine now and I can update.

> version: '2.1'
> 
> services:
> 
>   wordpress:
>     image: wordpress
>     restart: unless-stopped
>     ports:
>       - 5995:80
>     environment:
>       WORDPRESS_DB_HOST: db
>       WORDPRESS_DB_USER: ansred
>       WORDPRESS_DB_PASSWORD: heythere
>       WORDPRESS_DB_NAME: linkdb
>     volumes:
>       - /volume1/docker/WordPress/link/config/data:/var/www/html
>     links:
>       - db:db
> 
>   db:
>     image: mysql:latest
>     restart: unless-stopped
>     environment:
>       MYSQL_DATABASE: linkdb
>       MYSQL_USER: ansred
>       MYSQL_PASSWORD: heythere
>       MYSQL_RANDOM_ROOT_PASSWORD: '1'
>     volumes:
>       - /volume1/docker/WordPress/link/config/db:/var/lib/mysql
> 





Still wondering, where to add the `user: root` in the file?

**Comment by dani8art** [comment]
You can add the user to each service like:

```
  wordpress:
    user: root
    image: wordpress
```

**Comment by ansred** [comment]
It seems to be helping by access via SSH and make changes using vi, but not from the UI.

Even after added user: root

it's not creating the files based the PUID and GUID


![image](https://user-images.githubusercontent.com/5244872/102846619-759dab00-43de-11eb-90ca-bd19854093bb.png)


Is it possible to add those environments? or maybe another image of wordpress can do?

**Comment by dani8art** [comment]
Hi can you try to execute this?

```
$ sudo chown -R 1001:0 /volume1/docker/WordPress/food/config/data
$ sudo chmod -R g+rwX /volume1/docker/WordPress/food/config/data
```

**Comment by ansred** [comment]
@dani8art That did the trick by changing the owner user/group permission which is good.

![image](https://user-images.githubusercontent.com/5244872/103254842-f9164980-4954-11eb-8ef3-1743b61f1ee2.png)

And I was able to modify the file directly from the path and save it.

`/volume1/docker/WordPress/Start/config/data/wp-config.php`

now I can see the direct update option is available, but still having an issue writing again, which is strange since the root is owner!

![image](https://user-images.githubusercontent.com/5244872/103254903-42669900-4955-11eb-8442-dacdbf5f0d7f.png)

**Comment by javsalgar** [comment]
Hi, 

If you are running the container as root, then you need to make the files to be writable by the `daemon` user, otherwise it will not work. If you can enter the container and execute commands inside, you can try to do the chown manually from there.

**Comment by ansred** [comment]
You are right, I fixed the docker stack and everything is wokring smoothly now!'
Thanks loads for the help

Here is the docker stack in case anyone needed it

```
version: '2.1'

services:

  wordpress:
    user: root
    image: wordpress
    restart: unless-stopped
    ports:
      - 6996:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ansred
      WORDPRESS_DB_PASSWORD: heythere
      WORDPRESS_DB_NAME: rootdb
    volumes:
      - /volume1/docker/WordPress/root/config/data:/var/www/html
    links:
      - db:db

  db:
    user: root
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: rootdb
      MYSQL_USER: ansred
      MYSQL_PASSWORD: heythere
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - /volume1/docker/WordPress/root/config/db:/var/lib/mysql
```
