### ISSUE TITLE
Mysql to MariaDB

### ISSUE THREAD

**Issue by Larzack** [bitnami/bitnami-docker-wordpress#275]
Hi all;

I use Kubernetes and I have 4 Wordpress that I'm moving from Kubernetes 1.16 to Kubernetes 1.18.
I changed from 9.4.3 to 10.0.10 and come back to 9.4.3 because I have the same issue.
Previously I used MySQL.
I copy my MysqlDB to my new MariaDB server (export and import)

Now I have a MariaDB outside Kubernetes and network access are OK, I can do mysql queries using CLI.

My Pod don't start because it can't connect to my MariaDB. I have this error : 

```
 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment. 

│ nami    INFO  Initializing apache
│ nami    INFO  apache successfully initialized
│ nami    INFO  Initializing mysql-client
│ nami    INFO  mysql-client successfully initialized 
│ nami    INFO  Initializing wordpress 
│ wordpre INFO  ==> Preparing Varnish environment 
│ wordpre INFO  ==> Preparing Apache environment                                                  
│ wordpre INFO  ==> Preparing PHP environment                                                                                                                                                                                         
│ wordpre INFO  WordPress has been already initialized, restoring...                                                                                                                                                                   
│ mysql-c INFO  Trying to connect to MySQL server                                                                                                                                                                                      
│ Error executing 'postInstallation': Failed to connect to localhost:3306 after 36 tries                                                                                                                                               
│ stream closed  
```

This is my values 

```
wordpress:
  allowEmptyPassword: false
  externalDatabase:
    database: **********
    host: **********.eu-west-1.rds.amazonaws.com
    password: **********
    port: 3306
    user: **********
  ingress:
    annotations:
      cert-manager.io/cluster-issuer=letsencrypt-prod: null
      kubernetes.io/ingress.class=nginx: null
    enabled: true
    hostname: **********
    tls: true
  livenessProbe:
    enabled: false
  mariadb:
    enabled: false    
#    auth:
#      rootPassword: **********
#      password: **********
  persistence:
    enabled: true
    storageClass: efs-sc
    accessMode: ReadWriteMany
    size: 5Gi
  readinessProbe:
    enabled: false
  resources:
    requests:
      cpu: "0"
      memory: "0"
  wordpressBlogName: **********
  wordpressEmail: **********
  wordpressPassword: **********
  wordpressScheme: https
  wordpressSkipInstall: true
  wordpressUsername: **********
```

How to fix ?
Regards
