### ISSUE TITLE
WP Scheduler 

### ISSUE THREAD

**Issue by Bibelo** [bitnami/bitnami-docker-wordpress#280]
**Description**

Any newsletter plugin I install reports that "The WP scheduler doesn't seem to be running correctly" (newsletter, mailchimp, mailpoet).

**Note:** with Newsletter plugin, I can still send the mail when I "trigger" the sending.

Additionally, the **Site Health** keep issuing warnings:

> The REST API is one way WordPress, and other applications, communicate with the server. One example is the block editor screen, which relies on this to display, and save, your posts and pages.

> The REST API request failed due to an error.
`Error: cURL error 7: Failed to connect to xxx-dev.yyy.fr port 443: Connection refused (http_request_failed)`

**Note:** I was able to FIX a previous error message:

> The REST API encountered an error

> The REST API is one way WordPress, and other applications, communicate with the server. One example is the block editor screen, which relies on this to display, and save, your posts and pages.

> The REST API request failed due to an error.
`Error: cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received (http_request_failed)`

by adding the following line to my docker-compose.yml:
```
    extra_hosts:
      - "xxx-dev.yyy.fr:172.25.0.6"
```

**Steps to reproduce the issue:**

1. A simple docker-compose, adapted to be behind a NGINX Reverse Proxy (note the port mapping has been commented out)
```
version: '2'
services:
  xxx_mariadb_dev:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    container_name: xxx_mariadb_dev
    volumes:
      - '/data/web/xxx/dev/mariadb:/bitnami/mariadb'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_PASSWORD=XXX
      - MARIADB_ROOT_PASSWORD=XXX
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=no
    restart: always
    networks:
      - default

  mariage_wordpress_dev:
    image: 'docker.io/bitnami/wordpress:5-debian-10'
    container_name: xxx_wordpress_dev
    #user: root
    volumes:
      - '/data/web/xxx/dev/wordpress:/bitnami/wordpress'
    depends_on:
      - xxx_mariadb_dev
    environment:
      - MARIADB_HOST=xxx_mariadb_dev
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_PASSWORD=XXX
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=no
      - WORDPRESS_USERNAME=XXX
      - WORDPRESS_PASSWORD=XXX
      - WORDPRESS_EMAIL=XXX
      - WORDPRESS_FIRST_NAME=XXX
      - WORDPRESS_LAST_NAME=XXX
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=XXX
      - SMTP_PASSWORD=XXX
      - SMTP_PROTOCOL=tls
    restart: always
    extra_hosts:
      - "xxx-dev.yyy.fr:172.25.0.6"
    networks:
      - default

networks:
  default:
    external:
      name: config_default
```

2. A (finally!) working TLS NGINX Config:

```
server {
    listen 80;
    server_name xxx-dev.bartolone.fr;

    error_log /dev/stdout debug;
    access_log /dev/stdout;

    location / {
        return 301 https://$host$request_uri;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}

server {
    listen 443 ssl;
    server_name xxx-dev.yyy.fr;

    ssl_certificate /etc/letsencrypt/live/mariage-dev.bartolone.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mariage-dev.bartolone.fr/privkey.pem;

    error_log /dev/stdout debug;
    access_log /dev/stdout;

    location / {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_pass http://xxx_wordpress_dev:8080/;

client_max_body_size 80M;

    }

    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
```

3. NGINX is handling the TLS/SSL Let's Encrypt certificates, and redirecting to the bitnami wordpress container, which is listening on port 8080:
```
docker ps                                                                                                               ✔  158.69.1.138 IP  ⚡  993  12:52:43
IMAGE                            PORTS                                      NAMES
bitnami/wordpress:5-debian-10    8080/tcp, 8443/tcp                         xxx_wordpress_dev
```

4. The problem appears right out of the box.

Site Health showing errors
Newsletter showing error after installation.

Additionally, I wish I could program a cron instead, but crontab command is not installed in the container.

Thank you!

** Other info **

All of this is working on my own VPS.
I've got no other issue

**Version**

- Output of `docker version`:

```
docker version                                                                                                          ✔  158.69.1.138 IP  ⚡  994  12:53:44
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Wed Oct 14 19:00:27 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Oct 14 16:52:50 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.3
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 7
  Running: 7
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-123-generic
 Operating System: Ubuntu 18.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.899GiB
 Name: 
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: 
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
