### ISSUE TITLE
EACCES: permission denied, open '/.nami/registry.json'

### ISSUE THREAD

**Issue by JohnPreston** [bitnami/bitnami-docker-wordpress#281]
After pulling the docker-compose file via 
`curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-wordpress/master/docker-compose.yml`

I then add `user: 1001:1001` to the service definition for wordpress.

```yaml
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'docker.io/bitnami/wordpress:5-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
    user: 1001:1001

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

```
And I immediately get 

```bash
wordpress_1  | EACCES: permission denied, open '/.nami/registry.json'                                                                                                                                                
wordpress-demo_wordpress_1 exited with code 1  
```
**Version**

- Output of `docker version`:
```
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:34:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:32:09 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.28.4, build unknown
docker-py version: 4.4.3
CPython version: 3.7.9
OpenSSL version: OpenSSL 1.1.1g FIPS  21 Apr 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

This happens anywhere I run the container, as soon as I change the user.
Whether the driver is local or bind and then mounted to a local FS or not, always getting the same error.

Thanks for your help
