### ISSUE TITLE
Question: why does mounted wordpress wp-content dir does not "override" bitnami plugins?

### ISSUE THREAD

**Issue by Franz333** [bitnami/bitnami-docker-wordpress#286]
**Description**

I am learning Docker and I have been playing with bitnami-docker-wordpress that I would like to use for local dev purposes.

I thought that mounting my local wordpress files - wp-content - would simply remove the default plugins installed with Bitnami.

Why isn't it the case? 

I know I could `/opt/bitnami/wp-cli/bin/wp plugin delete + plugin name` inside the app-entrypoint.sh file to remove all default Bitnami plugins but that's not a permanent solution if that plugin list changes eventually. 

**Steps to reproduce the issue:**

1. git clone https://github.com/bitnami/bitnami-docker-wordpress.git
2. add existing wordpress files and database dump in the /5/debian-10 folder
3. give user 1001 permissions to the wp source folders and files: sudo chown 1001:1001 wp-source-dir -R
4. modify Dockerfile: WORDPRESS_SKIP_INSTALL="yes" and WORDPRESS_TABLE_PREFIX="custom_"
5. modify docker-compose.yml (see underneath)

**Describe the results you received:**

Bitnami default plugins are installed.

**Describe the results you expected:**

I expected the host mounted wp-content folder to "override" this folder in the wordpress container 

**Additional information you deem important (e.g. issue happens only occasionally):**

Here is my docker-compose.yml

```yaml
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    volumes:
      # Execute custom database dump at first run
      - ./wp-source-dir/db/:/docker-entrypoint-initdb.d/
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - MARIADB_USER=bn_wordpress
      # Change database name
      - MARIADB_DATABASE=local
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'docker.io/bitnami/wordpress:5-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      # Mount existing wp files
       - ./wp-source-dir/wp/wp-content:/bitnami/wordpress/wp-content
       - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      # Change database name
      - WORDPRESS_DATABASE_NAME=local
      # Add table prefix env variable
      - WORDPRESS_TABLE_PREFIX=custom_
      - ALLOW_EMPTY_PASSWORD=yes
      - BITNAMI_DEBUG=true
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:17:50 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 7
  Running: 2
  Paused: 0
  Stopped: 5
 Images: 15
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 4.525GiB
 Name: docker-desktop
 ID: MVEI:VPW2:GQEX:2J3Q:35FZ:4325:NNBA:YVUZ:XYGE:F6GT:W2NL:VL4F
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
I am on Windows 10 but I use Windows Subsystem for Linux (Ubuntu)
