### ISSUE TITLE
SMTP_*  environment variables are not read

### ISSUE THREAD

**Issue by frattallone** [bitnami/bitnami-docker-wordpress#289]
**Description**

I have updated SMTP_* environment variables in docker-compose.yml but these values are ignored.

**Steps to reproduce the issue:**

1. edit docker-compose.yml adding SMTP configuration:
```
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - WORDPRESS_SKIP_INSTALL=no
      - SMTP_HOST=my_host_1
      - SMTP_PASSWORD=my_password_1
      - SMTP_PORT=587
      - SMTP_PROTOCOL=tls
      - SMTP_USER=my_smtp_user_1
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: docker.io/bitnami/wordpress:5
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
```
2. run containers `docker-compose -f docker-compose.yml up`
3. attach to wordpress `docker-compose -f docker-compose.yml exec wordpress /bin/bash`
4. inpect wordpress configuration `nami inspect com.bitnami.wordpress`
```
{
  "id": "com.bitnami.wordpress",
  "name": "wordpress",
  "version": "5.7.1",
  "revision": "2",
  "installedAsRoot": true,
  "lifecycle": "unpacked",
  "installdir": "/opt/bitnami/wordpress",
  "installPrefix": "/opt/bitnami",
  "values": {
    "username": "user",
    "email": "user@example.com",
    "firstName": "FirstName",
    "lastName": "LastName",
    "blogName": "User's Blog!",
    "tablePrefix": "wp_",
    "htaccessOverrideNone": "yes",
    "htaccessPersistenceEnabled": "no",
    "databaseServerHost": "127.0.0.1",
    "databaseServerPort": 3306,
    "databaseName": "bitnami_wordpress",
    "databaseUser": "bn_wordpress",
    "databasePassword": "",
    "databaseSSLCAFile": "",
    "smtpUser": "",
    "smtpUsername": "",
    "smtpHost": "",
    "smtpPort": "",
    "smtpProtocol": "",
    "webServerUser": "daemon",
    "webServerGroup": "daemon",
    "httpPort": "8080",
    "httpsPort": "8443",
    "scheme": "http",
    "opcacheDashboardEnabled": "false",
    "extraWPConfigContent": "",
    "skipInstall": "no",
    "resetDataPermissions": "no",
    "dataToPersist": [
      "wp-content",
      "wp-config.php"
    ],
    "persistDir": "/bitnami/wordpress",
    "bnsupportPriv": "{{$app.installdir}}/wp-config.php",
    "bnsupportAcl": "{{$app.installdir}}",
    "phpMemoryLimit": "256M",
    "phpOpcacheEnabled": "yes"
  },
  "extends": [
    "Component"
  ],
  "environment": {},
  "exports": []
}
```

**Describe the results you received:**

- smtp variables are all empty
- *smtpPassword* is missing

```
    ...
    "smtpUser": "",
    "smtpUsername": "",
    "smtpHost": "",
    "smtpPort": "",
    "smtpProtocol": "",
    ...
```

**Describe the results you expected:**

smpt variables should be:

```
    ...
    "smtpPassword": "my_password_1",
    "smtpUser": "",
    "smtpUsername": "my_smtp_user_1",
    "smtpHost": "my_host_1",
    "smtpPort": "587",
    "smtpProtocol": "tls",
    ...
```

**Additional information you deem important (e.g. issue happens only occasionally):**

What's the difference between SMTP_USER and SMTP_USERNAME?
Why in readme you talk about WORDPRESS_SMTP_* in 

>In case the database already contains data from a previous WordPress installation, you need to set the variable WORDPRESS_SKIP_INSTALL to yes. Otherwise, the container would execute the installation wizard and could modify the existing data in the database. Note that, when setting WORDPRESS_SKIP_INSTALL to yes, the values WORDPRESS_USERNAME, WORDPRESS_PASSWORD, WORDPRESS_BLOG_NAME, WORDPRESS_EMAIL, WORDPRESS_BLOG_NAME and WORDPRESS_SMTP_* variables will be ignored. Make sure that, in this imported database, the table prefix matches the one set in WORDPRESS_TABLE_PREFIX.

How can I update these values? If I run:
```
nami initialize wordpress --inputs-file=/wordpress-inputs.json
Package wordpress seems to be already fully installed
```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 15
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 4.823GiB
 Name: docker-desktop
 ID: BMWI:3PQR:CGYS:RQRW:2OLJ:YSLR:SY7D:BEDY:2ZYJ:PEAH:AAA2:3V7A
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 60
  Goroutines: 69
  System Time: 2021-04-21T15:37:57.1380876Z
  EventsListeners: 4
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.5, build unknown
docker-py version: 4.4.0
CPython version: 3.8.1
OpenSSL version: OpenSSL 1.1.1i  8 Dec 2020
```
