### ISSUE TITLE
No such file or directory in /opt/bitnami/wordpress/wp-admin/includes/file.php on line 1092

### ISSUE THREAD

**Issue by Aerya** [bitnami/bitnami-docker-wordpress#293]
**Description**
Hi,
For a couple of weeks now I can't update any plugin.
`La mise à jour a échoué : Le téléchargement a échoué. Le dossier de destination pour la diffusion de fichier n’existe pas ou n’est pas accessible en écriture.`
`Mon May 17 14:58:10.929900 2021] [php7:warn] [pid 160] [client 172.17.0.1:38232] PHP Warning:  unlink(/opt/bitnami/wordpress/tmp/fr_FR-IJb9jA.tmp): No such file or directory in /opt/bitnami/wordpress/wp-admin/includes/file.php on line 1092, referer: https://upandclear.org/wp-admin/plugins.php`

I didn't change anything on the host.

**Steps to reproduce the issue:**

```
docker run -d \
--restart=always \
--name=BlogUaCWP \
-e PUID=0 \
-e PGID=0 \
-e MARIADB_HOST=xxx\
-e MARIADB_PORT_NUMBER=xxx\
-e WORDPRESS_DATABASE_USER=xxx\
-e WORDPRESS_DATABASE_NAME=xxx\
-e WORDPRESS_DATABASE_PASSWORD=xxx\
-e ALLOW_EMPTY_PASSWORD=no \
--link xxx\
-p xxx:8443 \
-v /home/aerya/docker/blog/uac/wp:/bitnami/wordpress \
--label=com.centurylinklabs.watchtower.enable=true \
bitnami/wordpress:latest
```

So WP is 5.7.2.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:05 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 24
  Running: 23
  Paused: 0
  Stopped: 1
 Images: 44
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-122-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 31.38GiB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

Thanks for help.

**Comment by carrodher** [comment]
I'm sorry but I am not able to reproduce the issue using a fresh installation.
Were you able to update plugins before? What are the permissions in the mounted path from the host (`/home/aerya/docker/blog/uac/wp`)? Did you change something in the container?

**Comment by mashirozx** [comment]
Same issue here, unable to install/upgrade plugins:
```
wordpress_1  | [Wed May 19 06:47:49.574490 2021] [php7:warn] [pid 156] [client 192.168.96.1:34710] PHP Warning:  unlink(/opt/bitnami/wordpress/tmp/wp-rest-api-controller.2.0.5-XARlRw.tmp): No such file or directory in /opt/bitnami/wordpress/wp-admin/includes/file.php on line 1092,
```

My config:
```yml
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    volumes:
      - ./db:/bitnami/mariadb
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'docker.io/bitnami/wordpress:5-debian-10'
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - ./app:/bitnami/wordpress
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_SKIP_INSTALL=yes
      - PHP_OPCACHE_ENABLED=no
  ```
permissions:
![image](https://user-images.githubusercontent.com/16148054/118768573-c04e2100-b8b1-11eb-91c3-9a0bf3f1f374.png)
![image](https://user-images.githubusercontent.com/16148054/118768608-cc39e300-b8b1-11eb-951a-8108a7fb1e05.png)
