### ISSUE TITLE
Helm Chart: Healthcheck fail when set wordpressScheme = 'https'

### ISSUE THREAD

**Issue by thanhtoan1196** [bitnami/bitnami-docker-wordpress#302]
Helmcheck: Healthcheck fail when set wordpressScheme = 'https'
Chart version: 11.0.15
Logs:
```
│ 10.42.0.1 - - [18/Jun/2021:04:31:32 +0000] "GET /wp-admin/install.php HTTP/1.1" 200 1294                                                                                                                               │
│ 10.42.0.1 - - [18/Jun/2021:04:31:33 +0000] "GET /wp-login.php HTTP/1.1" 302 -                                                                                                                                          │
│ 10.42.0.1 - - [18/Jun/2021:04:31:33 +0000] "\x16\x03\x01\x01" 400 226                                                                                                                                                  │
│ 10.42.0.1 - - [18/Jun/2021:04:31:42 +0000] "GET /wp-admin/install.php HTTP/1.1" 200 1294                                                                                                                               │
│ 10.42.0.1 - - [18/Jun/2021:04:31:43 +0000] "GET /wp-login.php HTTP/1.1" 302 -                                                                                                                                          │
│ 10.42.0.1 - - [18/Jun/2021:04:31:43 +0000] "\x16\x03\x01\x01" 400 226                                                                                                                                                  │
│ 10.42.0.1 - - [18/Jun/2021:04:31:52 +0000] "GET /wp-admin/install.php HTTP/1.1" 200 1294                                                                                                                               │
│ 10.42.0.1 - - [18/Jun/2021:04:31:53 +0000] "GET /wp-login.php HTTP/1.1" 302 -                                                                                                                                          │
│ 10.42.0.1 - - [18/Jun/2021:04:31:53 +0000] "\x16\x03\x01\x01" 400 226                                                                                                                                                  │
│ 10.42.0.1 - - [18/Jun/2021:04:32:02 +0000] "GET /wp-admin/install.php HTTP/1.1" 200 1294                                                                                                                               │
│ 10.42.0.1 - - [18/Jun/2021:04:32:03 +0000] "GET /wp-login.php HTTP/1.1" 302 -                                                                                                                                          │
│ 10.42.0.1 - - [18/Jun/2021:04:32:03 +0000] "\x16\x03\x01\x01" 400 226                                                                                                                                                  │
│ 10.42.0.1 - - [18/Jun/2021:04:32:12 +0000] "GET /wp-admin/install.php HTTP/1.1" 200 1294                                                                                                                               │
│ 10.42.0.1 - - [18/Jun/2021:04:32:13 +0000] "GET /wp-login.php HTTP/1.1" 302 -                                                                                                                                          │
│ 10.42.0.1 - - [18/Jun/2021:04:32:13 +0000] "\x16\x03\x01\x01" 400 226                                                                                                                                                  │
│ 10.42.0.1 - - [18/Jun/2021:04:32:22 +0000] "GET /wp-admin/install.php HTTP/1.1" 200 1294                                                                                                                               │
│ 10.42.0.1 - - [18/Jun/2021:04:32:23 +0000] "GET /wp-login.php HTTP/1.1" 302 -                                                                                                                                          │
│ 10.42.0.1 - - [18/Jun/2021:04:32:23 +0000] "\x16\x03\x01\x01" 400 226                                                                                                                                                  │
│ 10.42.0.1 - - [18/Jun/2021:04:32:32 +0000] "GET /wp-admin/install.php HTTP/1.1" 200 1294                                                                                                                               │
│ 10.42.0.1 - - [18/Jun/2021:04:32:33 +0000] "GET /wp-login.php HTTP/1.1" 302 -                                                                                                                                          │
│ 10.42.0.1 - - [18/Jun/2021:04:32:33 +0000] "\x16\x03\x01\x01" 400 226                                                                                                                                                  │
```

**Comment by migruiz4** [comment]
Hi @thanhtoan1196,

You would need to modify the readinessProbe and livenessProbe in the `values.yaml` adding `httpHeaders` as it follows:

```yaml
livenessProbe:
  enabled: true
  httpGet:
    path: /wp-admin/install.php
    port: http
    scheme: HTTP
    ## If using an HTTPS-terminating load-balancer, the probes may need to behave
    ## like the balancer to prevent HTTP 302 responses. According to the Kubernetes
    ## docs, 302 should be considered "successful", but this issue on GitHub
    ## (https://github.com/kubernetes/kubernetes/issues/47893) shows that it isn't.
    ## E.g.
    httpHeaders:
      - name: X-Forwarded-Proto
        value: https
    ##
    ## httpHeaders: []
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  httpGet:
    path: /wp-login.php
    port: http
    scheme: HTTP
    ## If using an HTTPS-terminating load-balancer, the probes may need to behave
    ## like the balancer to prevent HTTP 302 responses. According to the Kubernetes
    ## docs, 302 should be considered "successful", but this issue on GitHub
    ## (https://github.com/kubernetes/kubernetes/issues/47893) shows that it isn't.
    ## E.g.
    httpHeaders:
      - name: X-Forwarded-Proto
         value: https
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
```

The Readiness call return code is 302 (`"GET /wp-login.php HTTP/1.1" 302 `) which should be considered successful, but because of an issue with Kubernetes this workaround is needed.

If you need any further help please let me know.
