### ISSUE TITLE
How to set writing permissions for wp-config.php?

### ISSUE THREAD

**Issue by thanhtoan1196** [bitnami/bitnami-docker-wordpress#303]
I got this error when using WP Rocket plugin, how to fix it?

![image](https://user-images.githubusercontent.com/16433547/122635367-acdee180-d10d-11eb-824e-2a1c9a7224dc.png)

**Comment by miguelaeh** [comment]
Hi @thanhtoan1196 ,
Please check this https://github.com/bitnami/bitnami-docker-wordpress#532-debian-10-r30

**Comment by thanhtoan1196** [comment]
hi @miguelaeh , 
I see `No writing permissions will be granted on wp-config.php by default`
But how can I define `WP_CACHE` and still save even when stop, start container

**Comment by miguelaeh** [comment]
Hi @thanhtoan1196 ,
You can add options to the `wp-config.php` by using this env var`WORDPRESS_EXTRA_WP_CONFIG_CONTENT`

**Comment by thanhtoan1196** [comment]
hi @miguelaeh ,
I set `wordpressExtraConfigContent` for helm, and run `helm upgrade`, this is environment of container:
```
WORDPRESS_EXTRA_WP_CONFIG_CONTENT:      define( 'WP_CACHE', true );                                                                                                                                             
```
But when I check `/opt/bitnami/wordpress/wp-config.php`, it doesn't contain `define( 'WP_CACHE', true );`

**Comment by miguelaeh** [comment]
Hi @thanhtoan1196 ,
With the following docker-compose.yaml I can see it works properly:
```
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
  wordpress:
    image: docker.io/bitnami/wordpress:5
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_EXTRA_WP_CONFIG_CONTENT=define( 'WP_CACHE', true );
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
```

How are you setting that env var?
