### ISSUE TITLE
Cannot disable opcache with env variable

### ISSUE THREAD

**Issue by darrenbarklie** [bitnami/bitnami-docker-wordpress#304]
**Description**

Related to [Issue 120](https://github.com/bitnami/bitnami-docker-wordpress/issues/120), I am unable to disable the opcache setting for local development.

**Steps to reproduce the issue:**

1. Copy and bind a local `php.ini` to the container's `/opt/bitnami/php/lib/php.ini`
2. Set `PHP_ENABLE_OPCACHE=no` in docker-compose.yml file
3. `docker compose up`
4. Try to update volume mapped theme files, but caching is persistent in browser frontend
5. Attach shell to container, check `/opt/bitnami/php/lib/php.ini`, see `opcache` value is set to `1`

**Describe the results you received:**

`opcache.enable = 1` is affixed to the bottom of `php.ini` file

**Describe the results you expected:**

`opcache.enable = 0` is affixed to the bottom of `php.ini` file

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens consistency

**Version**

- Output of `docker version`:

```
  20.10.6
```

**Comment by pablogalegoc** [comment]
Hi @darrenbarklie!

If setting the `PHP_ENABLE_OPCACHE` like [this](https://github.com/bitnami/bitnami-docker-wordpress/issues/120#issuecomment-869387944) doesn't work let me know

**Comment by darrenbarklie** [comment]
Hey @pablogalegoc, @juan131 - Took a while for me to get back to this, however I can confirm that I am running a new container, with the following Dockerfile config:
```
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${WORDPRESS_DATABASE_NAME}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
  wordpress:
    image: docker.io/bitnami/wordpress:5
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
      # - './theme:/bitnami/wordpress/wp-content/themes/${WORDPRESS_DATABASE_NAME}'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_NAME=${WORDPRESS_DATABASE_NAME}
      - WORDPRESS_DATABASE_USER=${MARIADB_USER}
      - WORDPRESS_DATABASE_PASSWORD=${MARIADB_PASSWORD}
      - WORDPRESS_USERNAME=${WORDPRESS_USERNAME}
      - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
      - WORDPRESS_EMAIL=${WORDPRESS_EMAIL}
      - WORDPRESS_BLOG_NAME=${WORDPRESS_BLOG_NAME}
      - PHP_ENABLE_OPCACHE=no
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
```
When I navigate to `/opt/bitnami/php/lib/php.ini` I see no modification to the default `opcache.enable = 1`.

Thanks again for the support.
