### ISSUE TITLE
How to customize htaccess when working with an image in AWS ECS using Fargate?

### ISSUE THREAD

**Issue by tim-ellis** [bitnami/bitnami-docker-wordpress#305]
Hi, first posted about this in the bitnami community forum and was told to post here instead.

Here's my original question:

Hi, I’ve run into a CORS issue and need to add a line to htaccess in order to correct it. I’m running a bitnami/wordpress image inside of AWS ECS using Fargate so I’m not entirely sure how I would go about editing the htaccess file. Is there something I can do in the task definition json to add that file to the persistent storage volume so that it can be edited? I’ve tried adding the following to the environment variables but it doesn’t seem to have had an effect:

```
{
“name”: “WORDPRESS_ENABLE_HTACCESS_PERSISTENCE”,
“value”: “yes”
},
{
“name”: “WORDPRESS_HTACCESS_OVERRIDE_NONE”,
“value”: “no”
},
{
“name”: “WORDPRESS_DATA_TO_PERSIST”,
“value”: “wp-config.php wp-content .htaccess wordpress-htaccess.conf”
}
```

When I was asked to use the support tool I tried but it kept coming back with “Warning: The path does not seem to contain a valid Bitnami installation! Make sure you have proper access rights.”.

Thanks,
Tim

**Comment by juan131** [comment]
Hi @tim-ellis 

Thanks so much for bringing up this topic!

You shouldn't use the `WORDPRESS_DATA_TO_PERSIST`, it's enough using `WORDPRESS_ENABLE_HTACCESS_PERSISTENCE=yes` and `WORDPRESS_HTACCESS_OVERRIDE_NONE=yes` environment variables. BUT please note that these env. variables only have effect during the first initialization of the container. If you restart the container modifying these settings will be ignored.

> When I was asked to use the support tool I tried but it kept coming back with “Warning: The path does not seem to contain a valid Bitnami installation! Make sure you have proper access rights.”

Please note that the support tool is intended for Bitnami VMs, it's not compatible with our containers.

**Comment by tim-ellis** [comment]
Hi @juan131 ,

I modified the env variables to the following:

                {
                    "name": "WORDPRESS_ENABLE_HTACCESS_PERSISTENCE",
                    "value": "yes"
                },
                {
                    "name": "WORDPRESS_HTACCESS_OVERRIDE_NONE",
                    "value": "yes"
                }

But when I look in the mounted volume there is still no .htaccess file only wp-config.php and wp-content.  Am I missing something?  Do I need to manually add a .htaccess file in here?

Thanks,
Tim

**Comment by juan131** [comment]
I was unable to reproduce it using Docker COmpose @tim-ellis 

I used the Docker Compose below:

```yaml
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
  wordpress:
    image: docker.io/bitnami/wordpress:5
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_ENABLE_HTACCESS_PERSISTENCE=yes
      - WORDPRESS_HTACCESS_OVERRIDE_NONE=yes
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
```

As you can see, the `wordpress-htaccess.conf` is persisted in the `/bitnami/wordpress` directory (the directory where the persistent volume is mounted).

```console
$ docker-compose exec wordpress bash
I have no name!@wordpress:/$ ls -la /bitnami/wordpress/
total 24
drwxrwxr-x 3 daemon root 4096 Jul  1 06:11 .
drwxr-xr-x 3 root   root 4096 Jun 29 11:41 ..
-rw-r--r-- 1   1001 root  775 Jul  1 06:11 wordpress-htaccess.conf
-r--r----- 1   1001 root 4254 Jul  1 06:11 wp-config.php
drwxrwxr-x 7   1001 root 4096 Jul  1 06:11 wp-content
```
