### ISSUE TITLE
Download and Activate plugin in docker compose

### ISSUE THREAD

**Issue by AdilkhanKTR** [bitnami/bitnami-docker-wordpress#306]
Hi, how can i try to download and activate wordpress plugin in docker compose. Needed plugin: https://wordpress.org/plugins/amazon-s3-and-cloudfront/#description

```
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
  wordpress:
    image: docker.io/bitnami/wordpress:5
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_PLUGINS=`WP OFFLOAD MEDIA LITE 2.5.3`
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
```
i need use `- WORDPRESS_PLUGINS` in wordpress environment with value: `WP OFFLOAD MEDIA LITE 2.5.3` or i need user value `all`?

Can you give some examples please, 

Thank you.
