### ISSUE TITLE
[[QUESTION]] How can i deploy my project into wordpress

### ISSUE THREAD

**Issue by AdilkhanKTR** [bitnami/bitnami-docker-wordpress#308]
Hi guys, Im newbie in wordpress. I need to deploy my project into wordpress with docker-compose

I have finished project:
[project](https://ibb.co/HhZy0Nz)

static content like uploads/plugins/themes will be in the s3 bucket

how i can configure docker-compose.yml to automate this?

1. config files for web-page from [here](https://ibb.co/HhZy0Nz)
2. static content in the s3 bucket

Thank you

**Comment by rafariossaa** [comment]
Hi,
  You could persist Wordpress as indicated [here](https://github.com/bitnami/bitnami-docker-wordpress#user-content-persisting-your-application) and access the wordpress files in the directory used for persistence. 
  To use S3, you will need to use a plugin. I don't know which one would be best for you use case. I would suggest you to look into wordpress' forums where they could give you a better advice on this.

**Comment by AdilkhanKTR** [comment]
@rafariossaa 
When i try to you persistence for my project dir i have error:
`cp: cannot stat '/bitnami/wordpress/wp-config.php': Permission denied`
i tried to use 
`WORDPRESS_RESET_DATA_PERMISSIONS`
`user: root`

nothing doesn't work
```
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    volumes:
      - './mariadb:/test'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=wordpress
      - MARIADB_DATABASE=wordpress
  wordpress:
    image: docker.io/bitnami/wordpress:5
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - './web:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=wordpress
      - WORDPRESS_DATABASE_NAME=wordpress
      - WORDPRESS_PLUGINS=amazon-s3-and-cloudfront
      ```
