### ISSUE TITLE
Error: 'wp-config.php' not found when attaching volume

### ISSUE THREAD

**Issue by yenchieh** [bitnami/bitnami-docker-wordpress#313]
**Description**
I am trying to migrate from trellis/virtualBox WordPress setup to Docker, but I got an error `Error: 'wp-config.php' not found.` when I use volume to attach my local theme.
Here is the `docker-compose.yaml` file:
```yaml
version: "3.9"

services:
  db:
    image: mariadb:10.5
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: test
      MARIADB_PASSWORD: test-password
      MARIADB_DATABASE: test
      MARIADB_ROOT_PASSWORD: test-root-password
  wordpress:
    image: bitnami/wordpress:5.7.2
    depends_on:
      - db
    volumes:
      - wordpress_data:/bitnami/wordpress
      - ./site/web/app/themes/custom_theme:/bitnami/wordpress/wp-content/themes/custom_theme
      - ./site/web/app/mu-plugins:/bitnami/wordpress/wp-content/mu-plugins
      - ./custom_php.ini:/opt/bitnami/php/etc/conf.d/custom.ini
    ports:
      - "80:8080"
    restart: always
    environment:
      WORDPRESS_DATABASE_HOST: db
      WORDPRESS_DATABASE_PORT_NUMBER: 3306
      WORDPRESS_DATABASE_USER: test
      WORDPRESS_BLOG_NAME: test
      WORDPRESS_DATABASE_PASSWORD: test-password
      WORDPRESS_DATABASE_NAME: test
      WORDPRESS_USERNAME: test
      WORDPRESS_PASSWORD: test-password
      WORDPRESS_EMAIL: jay
      WORDPRESS_MEMORY_LIMIT: 1024M
      WORDPRESS_ENABLE_MULTISITE: "yes"
      WORDPRESS_MULTISITE_HOST: "nulab.test"
      WORDPRESS_MULTISITE_EXTERNAL_HTTP_PORT_NUMBER: 80
      WORDPRESS_MULTISITE_NETWORK_TYPE: subdirectory
      WORDPRESS_MULTISITE_FILEUPLOAD_MAXK: 1000000
      WORDPRESS_ENABLE_HTTPS: "no"
      PHP_ENABLE_OPCACHE: "no"
      WORDPRESS_PLUGINS: "
      advanced-custom-fields
      ,wordpress-popular-posts
      ,amazon-s3-and-cloudfront
      ,amazon-web-services
      ,custom-post-type-ui"
      PHP_UPLOAD_MAX_FILESIZE: 50M
      PHP_MEMORY_LIMIT: 1024M
volumes:
  db_data:
  wordpress_data:

```
If I have these two volumes
```yaml
      - ./site/web/app/themes/nulab-inc:/bitnami/wordpress/wp-content/themes/custom_theme
      - ./site/web/app/mu-plugins:/bitnami/wordpress/wp-content/mu-plugins
```
enabled, it won't work.

The workaround is to run `docker-compose up -d` without the above volume for the first time, once the WordPress is set up, I am able to enable the volumes and restart the service.

**Steps to reproduce the issue:**

1. Set docker volume with a local theme
2. Run `docker-compose up -d` 
3. The error `Error: 'wp-config.php' not found.` will show up on the log

**Describe the results you received:**
After `Error: 'wp-config.php' not found.` showing up, the service restart again.
The full logs:
```
wordpress 21:50:56.43 
wordpress 21:50:56.43 Welcome to the Bitnami wordpress container
wordpress 21:50:56.43 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
wordpress 21:50:56.43 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues
wordpress 21:50:56.44 
wordpress 21:50:56.44 INFO  ==> ** Starting WordPress setup **
wordpress 21:50:56.47 INFO  ==> Configuring PHP options
wordpress 21:50:56.47 INFO  ==> Setting PHP opcache.enable option
wordpress 21:50:56.48 INFO  ==> Setting PHP memory_limit option
wordpress 21:50:56.49 INFO  ==> Setting PHP upload_max_filesize option
wordpress 21:50:56.51 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
wordpress 21:50:56.73 WARN  ==> Hostname nulab.test could not be resolved, this could lead to connection issues
wordpress 21:50:56.87 INFO  ==> Restoring persisted WordPress installation
wordpress 21:50:56.90 INFO  ==> Trying to connect to the database server
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
```

**Describe the results you expected:**
The WordPress server starts properly with local themes attached as volume.

**Additional information you deem important (e.g. issue happens only occasionally):**
I also tried to build a new image and copy the custom theme to the image with the following code:
```
COPY ./site/web/app/themes/custom_theme /bitnami/wordpress/wp-content/themes/custom_theme
```
The build was successful, but when I run the image, it has the same error.

**Version**

- Output of `docker version`:

```
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df35096d
 Built:             Fri Jun  4 08:14:39 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.4
  Git commit:       b0f5bc36fe
  Built:            Fri Jun  4 08:14:24 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.5.2
  GitCommit:        36cc874494a56a253cd181a1a685b44b58a2e34a.m
 runc:
  Version:          1.0.0
  GitCommit:        v1.0.0-0-g84113eef
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-tp-docker)

Server:
 Containers: 15
  Running: 1
  Paused: 0
  Stopped: 14
 Images: 164
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 36cc874494a56a253cd181a1a685b44b58a2e34a.m
 runc version: v1.0.0-0-g84113eef
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.49-1-MANJARO
 Operating System: Manjaro Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.29GiB
 Name: Jay-manjaro
 ID: FAK3:WCHR:5E4Q:FMTS:2UGD:ENAD:MABX:YYWT:WO3P:GEBT:3SHN:NZ2Z
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: jack08300
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.28.4, build cabd5cfb
docker-py version: 4.4.3
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

```
