### ISSUE TITLE
Failed to upgrade Wordpress Multisite network 

### ISSUE THREAD

**Issue by system1system2** [bitnami/bitnami-docker-wordpress#314]
Hi. 

I modified docker-compose.yml to enable WordPress Multisite as follows:

```
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    volumes:
      - /Users/xyz/Docker/persistence/mariadb_data:/bitnami/mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
  wordpress:
    image: docker.io/bitnami/wordpress:latest
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - /Users/xyz/Docker/persistence/wordpress_data:/bitnami/wordpress
    depends_on:
      - mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_ENABLE_MULTISITE=yes
      - WORDPRESS_MULTISITE_HOST=test.com      # WordPress hostname. Only used for Multisite installations. No defaults.
      - WORDPRESS_HTACCESS_OVERRIDE_NONE=no
      - WORDPRESS_ENABLE_HTACCESS_PERSISTENCE=yes   # It will persist /opt/bitnami/wordpress/.htaccess
```

It works fine. I have a fully functional WPMU where I can set up and initialize multiple subdomains (inclusive of domain mapping). Thanks for that. 

The only thing that doesn't work is the network upgrade. 

Steps to reproduce:

1. Log in to the root domain of the WPMU installation. In my case: `http://test.com/wp-admin`
2. Create a new subdomain with a new domain mapping (the domain mapping part is not critical. I'm just reproducing my exact scenario). Let's say `research.test.com` mapped to `research.com`. 
3. Be sure that your WPMU network now has at least 2 sites.
4. Navigate to the network administration section of the root domain. In my case: `http://test.com/wp-admin/network/`
5. From the left sidebar, click `Upgrade Network`
6. Click on the blue button `Upgrade Network`

At this point, you'll see the following error:

```
http://research.com
Warning! Problem updating http://research.com. Your server may not be able to connect to sites running on it. Error message: cURL error 7: Failed to connect to research.com port 80: Connection refused
```

I think this depends on the fact that the Bitnami docker-compose.yml has published the WordPress container on port 8080.  

I tried to modify the docker-compose.yml file to publish on port 80:

```
     ports:
      - '80:80'
```

but the Wordpress installation stopped serving pages. I think it has to do with the fact that this container is run by a non-root user. 

Not sure how to proceed.

Thanks for any help.
