### ISSUE TITLE
The volume/mount folder changes are very slow, any idea?

### ISSUE THREAD

**Issue by CodeExplore** [bitnami/bitnami-docker-wordpress#317]
Hi everbody,

My docker-compose.yml is so:

 ```yaml
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
  wordpress:
    image: docker.io/bitnami/wordpress:5
    ports:
      - '1000:8080'
      - '1443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
      - './my-plugin:/bitnami/wordpress/wp-content/plugins/my-plugin'
    depends_on:
      - mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
volumes:
  mariadb_data:
  wordpress_data:

```

**The problem is**: When I edit any file in "my-plugin" folder it's apply within 1-2 minutes (not in seconds). I'm refreshing many times for see that edit in the WordPress. What is the problem?

Docker Engine Version: 20.10.8
