### ISSUE TITLE
Very slow worpderss

### ISSUE THREAD

**Issue by polRk** [bitnami/bitnami-docker-wordpress#320]
**Description**
Using default docker-compose.yml

Container log
```
192.168.48.1 - - [12/Aug/2021:19:27:44 +0000] "GET /wp-admin/options-general.php HTTP/1.1" 200 16192
2021-08-12T19:27:55.902965981Z 192.168.48.1 - - [12/Aug/2021:19:27:55 +0000] "GET /wp-admin/load-styles.php?c=0&dir=ltr&load%5Bchunk_0%5D=dashicons,admin-bar,common,forms,admin-menu,dashboard,list-tables,edit,revisions,media,themes,about,nav-menus,wp-pointer,widgets&load%5Bchunk_1%5D=,site-icon,l10n,buttons,wp-auth-check&ver=5.8 HTTP/1.1" 200 97499
2021-08-12T19:27:56.006563016Z 192.168.48.1 - - [12/Aug/2021:19:27:56 +0000] "GET /wp-admin/images/spinner-2x.gif HTTP/1.1" 200 7536
2021-08-12T19:28:02.932025619Z 192.168.48.1 - - [12/Aug/2021:19:27:42 +0000] "GET /wp-admin/admin-ajax.php?action=dashboard-widgets&widget=dashboard_primary&pagenow=dashboard HTTP/1.1" 200 523
2021-08-12T19:28:38.463500429Z 192.168.48.1 - - [12/Aug/2021:19:28:28 +0000] "GET /wp-admin/plugins.php HTTP/1.1" 200 17945
```

**Steps to reproduce the issue:**

1. docker-compose up -d
2. go to localhost:80
3. login

**Describe the results you received:**

Very slow wordpress

**Describe the results you expected:**

Fast like docker/wordperss

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 27
  Running: 2
  Paused: 0
  Stopped: 25
 Images: 248
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.36GiB
 Name: docker-desktop
 ID: UTCY:HT3R:HQM6:LDYW:BQOK:Y2T2:EVPC:MWXM:O6SJ:RCHT:TQJC:NAL6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false


```

- Output of `docker-compose version` (if applicable):

```
FROM bitnami/wordpress

ENV WORDPRESS_DATA_TO_PERSIST="wp-config.php wp-content/uploads"

COPY ./wp-content/themes/ /opt/bitnami/wordpress/wp-content/themes/
COPY ./wp-content/plugins/ /opt/bitnami/wordpress/wp-content/plugins/
```

```

version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
  wordpress:
    build: .
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
```

Docker for Mac (docker resources 12 GB, 8 cpu)
