### ISSUE TITLE
cannot access admin page on local multisite setup

### ISSUE THREAD

**Issue by M3psipax** [bitnami/bitnami-docker-wordpress#346]
### Name and Version

bitnami/wordpress:5.9.2

### What steps will reproduce the bug?

Setting up bitnami Wordpress locally on Windows 10 using `docker-compose up -d` with basically the default docker config extended with multisite env vars like this: 

```yaml
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
  wordpress:
    image: docker.io/bitnami/wordpress:5
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_ENABLE_MULTISITE=yes
      - WORDPRESS_MULTISITE_HOST=wpmulti.de
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
```

I tried different hostnames with and without adding them in my `hosts` for `127.0.0.1`
If I'm missing something about how to get this running locally, maybe there should be an extension to the guide.

### What is the expected behavior?

Be able to go to "localhost/wp-admin" or "wpmulti.de/wp-admin" to be able to setup websites.

### What do you see instead?

site cannot be reached at all. going to "localhost/wp-admin" or "wp-multi.de/wp-admin" produces

`This site can’t be reached Check if there is a typo in wpmulti.de.
If spelling is correct, [try running Windows Network Diagnostics](javascript:diagnoseErrors()).
DNS_PROBE_FINISHED_NXDOMAIN`

in chrome

### Additional information

I want to add that I was able use the bitnami multisite installer to set it up exactly like this. I was able to reach all pages for "wpmulti.de" and "subdomain.wpmulti.de" as soon as I added those in the hosts file. So there must be something about the docker setup that has this not working.
