### ISSUE TITLE
created new files in /opt/bitnami/wordpress

### ISSUE THREAD

**Issue by alianjo** [bitnami/bitnami-docker-wordpress#347]
### Name and Version

5.9.3-debian-10-r22 release

### What steps will reproduce the bug?

if your Wordpress creates some files (for instance robots.txt )  in `/opt/bitnami/wordpress` path they will not be persisted and if the container restarts that files will be lost.

### What do you see instead?

there is the same issue in Bitnami Wordpress Nginx

**Comment by rafariossaa** [comment]
Hi,
  I think in this case you could use [this parameter](https://github.com/bitnami/bitnami-docker-wordpress#user-content-user-and-site-configuration) `WORDPRESS_DATA_TO_PERSIST`.
  Could you give it a try ?

**Comment by alianjo** [comment]
Hi @rafariossaa for the first time when I want to setup the container it does not work.
![image](https://user-images.githubusercontent.com/69678339/165256165-0baf1a0f-06a5-4466-ab60-3e749467de63.png)

**Comment by rafariossaa** [comment]
Hi,
This is what I did:
- Use the following `docker-compose.yaml` (it is the default one but using directories for the volumes):
```
ersion: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - './mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
  wordpress:
    image: docker.io/bitnami/wordpress:5
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - './wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      #- WORDPRESS_DATA_TO_PERSIST=wp-config.php wp-content robots.txt
```
- Create the directories and change permission:
```
$ mkdir mariadb_data wordpress_data
$ sudo chmod 777 mariadb_data wordpress_data
```
- Start the compose and wait until it is up
```
$ docker-compose up
...
wordpress_1  | wordpress 07:59:40.48 INFO  ==> ** WordPress setup finished! **
wordpress_1  | wordpress 07:59:40.50 INFO  ==> ** Starting Apache **
wordpress_1  | [Wed Apr 27 07:59:40.709260 2022] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
```
- Stop it and uncomment the `WORDPRESS_DATA_TO_PERSIST` line in the docker-compose.yaml file.
- Create a sample `robots.txt` file and set permissions:
```
$ cat > wordpress_data/robots.txt <<EOF
> User-agent: *
> Disallow: /wp-admin/
> Disallow: /wp-login.php
> EOF

$ sudo chown 1001:root wordpress_data/robots.txt 
```
- Start the compose again and test the robots.txt url:
```
$ docker-compose up
....
$ curl http://localhost:80/robots.txt
User-agent: *
Disallow: /wp-admin/
Disallow: /wp-login.php
```
