### ISSUE TITLE
handling of links in Wordpress, http/https 

### ISSUE THREAD

**Issue by sadrian80** [bitnami/bitnami-docker-wordpress#354]
### Name and Version

bitnami/wordpress:6

### What steps will reproduce the bug?

This is not a bug.

I'm running a bn_WP container behind a Nginx reverse proxy. The proxy handles (and forces) SSL and routes request to port 8080.

### What is the expected behavior?

 When uploading assets to the Wordpress Media library and linking those, they will be linked insecure via http:// resulting in the errors on the page.

### What do you see instead?

 I assume this scenario to be quite common – how is this handled? If I change wp-config.php to https://, do I need to issue a certificate for the container itself, too?

**Comment by migruiz4** [comment]
Hi @sadrian80,

I found this link to the official documentation may help you with your use case: https://wordpress.org/support/article/administration-over-ssl/#using-a-reverse-proxy
And this other related issue: https://wordpress.org/support/topic/wp-behind-reverse-proxy-all-content-insecure/

You can set the configuration needed to `wp-config` by using the environment variable `WORDPRESS_EXTRA_WP_CONFIG_CONTENT`.

For example:
```yaml
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
  wordpress:
    image: docker.io/bitnami/wordpress:6
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - BITNAMI_DEBUG=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_EXTRA_WP_CONFIG_CONTENT=
         define('FORCE_SSL_ADMIN', true);

         if (strpos($$_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false)

         $$_SERVER['HTTPS']='on';

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
```
