### ISSUE TITLE
if php by path. php.ini cannot modification.

### ISSUE THREAD

**Issue by qoli** [bitnami/bitnami-docker-wordpress#66]
i check php.ini in /opt/bitnami/php/lib.
but not.

at last, i "docker exec" input docker, and build a soft link.
`ls -s /opt/.../php/conf/php.ini  /opt/bitnami/php/lib/php`

so that, php.ini is work.

my **docker-compose.yml**
```
version: '2'
services:
  mariadb:
    image: bitnami/mariadb:latest
    volumes:
      - /home/ubuntu/wp/mariadb-persistence:/bitnami/mariadb
  wordpress:
    image: bitnami/wordpress:latest
    depends_on:
      - mariadb
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /home/ubuntu/wp/wordpress-persistence:/bitnami/wordpress
      - /home/ubuntu/wp/apache-persistence:/bitnami/apache
      - /home/ubuntu/wp/php-persistence:/bitnami/php

```
