### ISSUE TITLE
Problem for connect to MySQL server

### ISSUE THREAD

**Issue by LeG3nDz** [bitnami/bitnami-docker-wordpress#88]
##### Description
After run `docker-compose up`, i've MariaDB error :

```
Creating wordpress_mariadb_1
Creating wordpress_wordpress_1
Attaching to wordpress_mariadb_1, wordpress_wordpress_1
mariadb_1    |
mariadb_1    | Welcome to the Bitnami mariadb container
mariadb_1    | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1    | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1    | Send us your feedback at containers@bitnami.com
mariadb_1    |
mariadb_1    | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
wordpress_1  |
wordpress_1  | Welcome to the Bitnami wordpress container
wordpress_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
wordpress_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues
wordpress_1  | Send us your feedback at containers@bitnami.com
wordpress_1  |
mariadb_1    | nami    INFO  Initializing mariadb
mariadb_1    | mariadb INFO  ==> Configuring permissions...
mariadb_1    | mariadb INFO  ==> Validating inputs...
mariadb_1    | mariadb WARN  Allowing the "rootPassword" input to be empty
wordpress_1  | nami    INFO  Initializing apache
wordpress_1  | apache  INFO  ==> Patching httpoxy...
wordpress_1  | nami    INFO  apache successfully initialized
wordpress_1  | nami    INFO  Initializing php
wordpress_1  | nami    INFO  php successfully initialized
wordpress_1  | nami    INFO  Initializing mysql-client
wordpress_1  | nami    INFO  mysql-client successfully initialized
wordpress_1  | nami    INFO  Initializing wordpress
mariadb_1    | mariadb INFO  ==> Initializing database...
mariadb_1    | mariadb INFO  ==> Creating 'root' user with unrestricted access...
mariadb_1    | mariadb INFO  ==> Enabling remote connections...
mariadb_1    | mariadb INFO
mariadb_1    | mariadb INFO  ########################################################################
mariadb_1    | mariadb INFO   Installation parameters for mariadb:
mariadb_1    | mariadb INFO     Root User: root
mariadb_1    | mariadb INFO     Root Password: Not set during installation
mariadb_1    | mariadb INFO   (Passwords are not shown for security reasons)
mariadb_1    | mariadb INFO  ########################################################################
mariadb_1    | mariadb INFO
mariadb_1    | nami    INFO  mariadb successfully initialized
mariadb_1    | INFO  ==> Starting mariadb...
mariadb_1    | nami    ERROR Unable to start com.bitnami.mariadb: Warning: World-writable config file '/opt/bitnami/mariadb/conf/my.cnf' is ignored
mariadb_1    | Warning: World-writable config file '/opt/bitnami/mariadb/conf/my.cnf' is ignored
mariadb_1    |
wordpress_mariadb_1 exited with code 1
wordpress_1  | mysql-c INFO  Trying to connect to MySQL server
wordpress_1  | Error executing 'postInstallation': Failed to connect to mariadb:3306 after 36 tries
wordpress_wordpress_1 exited with code 1
```

###### Output of `docker version`:
```
time="2017-03-13T16:44:12+01:00" level=warning msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

###### Output of `docker info`:
```
time="2017-03-13T16:43:35+01:00" level=warning msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
Containers: 30
 Running: 0
 Paused: 0
 Stopped: 30
Images: 37
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 261
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.43-boot2docker
Operating System: Boot2Docker 1.13.0 (TCL 7.2); HEAD : 5b8d9cb - Wed Jan 18 18:50:40 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8 MiB
Name: default
ID: S6SA:7NW7:AACJ:4DVP:Y6BX:EJDM:22BG:ME2V:5ICL:F5TX:SXBE:HGFH
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 14
 Goroutines: 23
 System Time: 2017-03-13T15:43:35.742809403Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

###### Output of `docker-compose version` (if applicable):
```
docker-compose version 1.10.0, build 4bd6f1a0
docker-py version: 2.0.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

Do you have any idea ?

Thank you community ! :)

**Comment by silviofdez** [comment]
We have not been able to reproduce your issue.

Could you try to delete your `wordpress` and `mariadb` images, donwload again our docker-compose and let us know if it works?

Thank you for the feedback.

**Comment by LeG3nDz** [comment]
Hi @silviofdez 

I've test your solution, but no result. Maybe because i'm on Windows ? I will try on Ubuntu tonight :/

**Comment by silviofdez** [comment]
It is weird, are you using docker for windows or dockertools?

**Comment by LeG3nDz** [comment]
I use Docker Quickstart Terminal, on Windows 10

**Comment by LeG3nDz** [comment]
@silviofdez 

Work nice on Linux, the problem is only on Windows :(

My docker-compose for persisting application :

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './mariadb:/bitnami/mariadb'
  redmine:
    image: 'bitnami/redmine:latest'
    ports:
      - '80:3000'
    volumes:
      - './redmine:/bitnami/redmine'
    depends_on:
      - mariadb
```

**Comment by BBavouzet** [comment]
Hi,
I've got same problem :
`wordpress_1  | mysql-c INFO  Trying to connect to MySQL server
wordpress_1  | Error executing 'postInstallation': Failed to connect to localhost:3306 after 36 tries
testwdps_wordpress_1 exited with code 1`
Wordpress tries to connect at localhost. I think my docker-compose variables have no effect.
`version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - '/home/benoit/test/testwdps:/bitnami/mariadb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=mydbname
      - MYSQL_CLIENT_CREATE_DATABASE_USER=mydb
      - MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=mydb
  wordpress:
    image: 'bitnami/wordpress:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/home/benoit/test/testwdps:/bitnami/wordpress'
      - '/home/benoit/test/testwdps:/bitnami/apache'
      - '/home/benoit/test/testwdps:/bitnami/php'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT=3306
      - WORDPRESS_DATABASE_USER=mydb
      - WORDPRESS_DATABASE_PASSWORD=mydb
      - WORDPRESS_DATABASE_NAME=mydbname
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_USERNAME=me
      - WORDPRESS_PASSWORD=my_password
      - WORDPRESS_EMAIL=my@mail.fr
      - WORDPRESS_FIRST_NAME=myfirstname
      - WORDPRESS_LAST_NAME=mylastname
      - WORDPRESS_BLOG_NAME=blogname
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local
`
In my local directorie, the wp-config parameters are by defaults.
Could you help me? I'm docker beginner, maybe I've make mistaks
Benoît

**Comment by jotadrilo** [comment]
Hey @BBavouzet,

The `mysql-client` module is shipped within the `wordpress` image. You set the `MYSQL_CLIENT_CREATE_DATABASE_` env vars in the `mariadb` image, that's why you get this error:

> Failed to connect to localhost:3306 after 36 tries

That module is using the default values when initializing so it tries to look for the database to connect with in `localhost`

However, as you are using the `mariadb` image, you can use the following env variables instead:

```yml
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - '/home/benoit/test/testwdps:/bitnami/mariadb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=mydbname
      - MARIADB_USER=mydb
      - MARIADB_PASSWORD=mydb
```

In that way you don't need to set the `ALLOW_EMPTY_PASSWORD=yes` env var in the `wordpress` environment section. That env var allows wordpress to use a database with blank password and mysql-client to create a database with blank password.

I'm pasting below the full docker-compose specs:

```yml
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - '/home/benoit/test/testwdps:/bitnami/mariadb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=mydbname
      - MARIADB_USER=mydb
      - MARIADB_PASSWORD=mydb
  wordpress:
    image: 'bitnami/wordpress:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/home/benoit/test/testwdps:/bitnami/wordpress'
      - '/home/benoit/test/testwdps:/bitnami/apache'
      - '/home/benoit/test/testwdps:/bitnami/php'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT=3306
      - WORDPRESS_DATABASE_USER=mydb
      - WORDPRESS_DATABASE_PASSWORD=mydb
      - WORDPRESS_DATABASE_NAME=mydbname
      - WORDPRESS_USERNAME=me
      - WORDPRESS_PASSWORD=my_password
      - WORDPRESS_EMAIL=my@mail.fr
      - WORDPRESS_FIRST_NAME=myfirstname
      - WORDPRESS_LAST_NAME=mylastname
      - WORDPRESS_BLOG_NAME=blogname
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local
```

Could you verify if this configuration works for you?

**Comment by jotadrilo** [comment]
Hey @LeG3nDz,

I cannot reproduce this issue on Windows, but it seems quite similar to an old issue with the MySQL configuration file. Could you try to run a custom image?

1. Edit the `4/rootfs/app-entrypoint.sh` file
2. Add the following `chmod` command before the `exec tini -- "$@"` line:

```
chmod 0644 /opt/bitnami/mariadb/conf/my.cnf

exec tini -- "$@"
```

3. Rebuild the image with `docker build -t bitnami/mariadb:latest -t 4/Dockerfile 4`. 
  > **NOTE:** I set the `latest` tag in the command, you may want to use the proper tag depending on the `docker-compose.yml` you are running (see the `image: bitnami/mariadb:TAG` section for the mariadb service)
4. Run the docker-compose command again

Could you confirm if this help?

**Comment by BBavouzet** [comment]
Hey @jotadrilo,

Thank you very much ! This configuration works for me !
I think, I've understanded my mistakes, thanks to you!

Benoît

**Comment by LeG3nDz** [comment]
Hi @jotadrilo 

This work for me too ! Thank you !

**Comment by bloodcarter** [comment]
I have the same problem, and the @jotadrilo's solution didn't help. But I have this error:
```
wordpress_1  | Error executing 'postInstallation': Failed to connect to localhost:3306 after 36 tries
```

Can't understand why wordpress container tries to connect to localhost, instead mariadb.

The yml is:
```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - './mariadb_data:/bitnami'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './wordpress_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
```
